
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Files` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Files
 * 
 */
export type FilesModel = runtime.Types.Result.DefaultSelection<Prisma.$FilesPayload>

export type AggregateFiles = {
  _count: FilesCountAggregateOutputType | null
  _avg: FilesAvgAggregateOutputType | null
  _sum: FilesSumAggregateOutputType | null
  _min: FilesMinAggregateOutputType | null
  _max: FilesMaxAggregateOutputType | null
}

export type FilesAvgAggregateOutputType = {
  size: number | null
  width: number | null
  height: number | null
}

export type FilesSumAggregateOutputType = {
  size: number | null
  width: number | null
  height: number | null
}

export type FilesMinAggregateOutputType = {
  id: string | null
  originalname: string | null
  extension: string | null
  mimeType: string | null
  size: number | null
  width: number | null
  height: number | null
  checksum: string | null
  blurhash: string | null
  dominantColor: string | null
  filePath: string | null
  folderId: string | null
  userId: string | null
  isPublic: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FilesMaxAggregateOutputType = {
  id: string | null
  originalname: string | null
  extension: string | null
  mimeType: string | null
  size: number | null
  width: number | null
  height: number | null
  checksum: string | null
  blurhash: string | null
  dominantColor: string | null
  filePath: string | null
  folderId: string | null
  userId: string | null
  isPublic: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FilesCountAggregateOutputType = {
  id: number
  originalname: number
  extension: number
  mimeType: number
  size: number
  width: number
  height: number
  checksum: number
  blurhash: number
  dominantColor: number
  filePath: number
  folderId: number
  userId: number
  isPublic: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type FilesAvgAggregateInputType = {
  size?: true
  width?: true
  height?: true
}

export type FilesSumAggregateInputType = {
  size?: true
  width?: true
  height?: true
}

export type FilesMinAggregateInputType = {
  id?: true
  originalname?: true
  extension?: true
  mimeType?: true
  size?: true
  width?: true
  height?: true
  checksum?: true
  blurhash?: true
  dominantColor?: true
  filePath?: true
  folderId?: true
  userId?: true
  isPublic?: true
  createdAt?: true
  updatedAt?: true
}

export type FilesMaxAggregateInputType = {
  id?: true
  originalname?: true
  extension?: true
  mimeType?: true
  size?: true
  width?: true
  height?: true
  checksum?: true
  blurhash?: true
  dominantColor?: true
  filePath?: true
  folderId?: true
  userId?: true
  isPublic?: true
  createdAt?: true
  updatedAt?: true
}

export type FilesCountAggregateInputType = {
  id?: true
  originalname?: true
  extension?: true
  mimeType?: true
  size?: true
  width?: true
  height?: true
  checksum?: true
  blurhash?: true
  dominantColor?: true
  filePath?: true
  folderId?: true
  userId?: true
  isPublic?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type FilesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Files to aggregate.
   */
  where?: Prisma.FilesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Files to fetch.
   */
  orderBy?: Prisma.FilesOrderByWithRelationInput | Prisma.FilesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FilesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Files from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Files.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Files
  **/
  _count?: true | FilesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: FilesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: FilesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FilesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FilesMaxAggregateInputType
}

export type GetFilesAggregateType<T extends FilesAggregateArgs> = {
      [P in keyof T & keyof AggregateFiles]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFiles[P]>
    : Prisma.GetScalarType<T[P], AggregateFiles[P]>
}




export type FilesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FilesWhereInput
  orderBy?: Prisma.FilesOrderByWithAggregationInput | Prisma.FilesOrderByWithAggregationInput[]
  by: Prisma.FilesScalarFieldEnum[] | Prisma.FilesScalarFieldEnum
  having?: Prisma.FilesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FilesCountAggregateInputType | true
  _avg?: FilesAvgAggregateInputType
  _sum?: FilesSumAggregateInputType
  _min?: FilesMinAggregateInputType
  _max?: FilesMaxAggregateInputType
}

export type FilesGroupByOutputType = {
  id: string
  originalname: string
  extension: string
  mimeType: string
  size: number
  width: number | null
  height: number | null
  checksum: string | null
  blurhash: string | null
  dominantColor: string | null
  filePath: string
  folderId: string | null
  userId: string
  isPublic: boolean
  createdAt: Date
  updatedAt: Date
  _count: FilesCountAggregateOutputType | null
  _avg: FilesAvgAggregateOutputType | null
  _sum: FilesSumAggregateOutputType | null
  _min: FilesMinAggregateOutputType | null
  _max: FilesMaxAggregateOutputType | null
}

type GetFilesGroupByPayload<T extends FilesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FilesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FilesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FilesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FilesGroupByOutputType[P]>
      }
    >
  >



export type FilesWhereInput = {
  AND?: Prisma.FilesWhereInput | Prisma.FilesWhereInput[]
  OR?: Prisma.FilesWhereInput[]
  NOT?: Prisma.FilesWhereInput | Prisma.FilesWhereInput[]
  id?: Prisma.StringFilter<"Files"> | string
  originalname?: Prisma.StringFilter<"Files"> | string
  extension?: Prisma.StringFilter<"Files"> | string
  mimeType?: Prisma.StringFilter<"Files"> | string
  size?: Prisma.IntFilter<"Files"> | number
  width?: Prisma.IntNullableFilter<"Files"> | number | null
  height?: Prisma.IntNullableFilter<"Files"> | number | null
  checksum?: Prisma.StringNullableFilter<"Files"> | string | null
  blurhash?: Prisma.StringNullableFilter<"Files"> | string | null
  dominantColor?: Prisma.StringNullableFilter<"Files"> | string | null
  filePath?: Prisma.StringFilter<"Files"> | string
  folderId?: Prisma.StringNullableFilter<"Files"> | string | null
  userId?: Prisma.StringFilter<"Files"> | string
  isPublic?: Prisma.BoolFilter<"Files"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Files"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Files"> | Date | string
  folder?: Prisma.XOR<Prisma.FoldersNullableScalarRelationFilter, Prisma.FoldersWhereInput> | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  variants?: Prisma.FileVariantsListRelationFilter
}

export type FilesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  originalname?: Prisma.SortOrder
  extension?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  size?: Prisma.SortOrder
  width?: Prisma.SortOrderInput | Prisma.SortOrder
  height?: Prisma.SortOrderInput | Prisma.SortOrder
  checksum?: Prisma.SortOrderInput | Prisma.SortOrder
  blurhash?: Prisma.SortOrderInput | Prisma.SortOrder
  dominantColor?: Prisma.SortOrderInput | Prisma.SortOrder
  filePath?: Prisma.SortOrder
  folderId?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  folder?: Prisma.FoldersOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
  variants?: Prisma.FileVariantsOrderByRelationAggregateInput
}

export type FilesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  filePath?: string
  AND?: Prisma.FilesWhereInput | Prisma.FilesWhereInput[]
  OR?: Prisma.FilesWhereInput[]
  NOT?: Prisma.FilesWhereInput | Prisma.FilesWhereInput[]
  originalname?: Prisma.StringFilter<"Files"> | string
  extension?: Prisma.StringFilter<"Files"> | string
  mimeType?: Prisma.StringFilter<"Files"> | string
  size?: Prisma.IntFilter<"Files"> | number
  width?: Prisma.IntNullableFilter<"Files"> | number | null
  height?: Prisma.IntNullableFilter<"Files"> | number | null
  checksum?: Prisma.StringNullableFilter<"Files"> | string | null
  blurhash?: Prisma.StringNullableFilter<"Files"> | string | null
  dominantColor?: Prisma.StringNullableFilter<"Files"> | string | null
  folderId?: Prisma.StringNullableFilter<"Files"> | string | null
  userId?: Prisma.StringFilter<"Files"> | string
  isPublic?: Prisma.BoolFilter<"Files"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Files"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Files"> | Date | string
  folder?: Prisma.XOR<Prisma.FoldersNullableScalarRelationFilter, Prisma.FoldersWhereInput> | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  variants?: Prisma.FileVariantsListRelationFilter
}, "id" | "filePath">

export type FilesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  originalname?: Prisma.SortOrder
  extension?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  size?: Prisma.SortOrder
  width?: Prisma.SortOrderInput | Prisma.SortOrder
  height?: Prisma.SortOrderInput | Prisma.SortOrder
  checksum?: Prisma.SortOrderInput | Prisma.SortOrder
  blurhash?: Prisma.SortOrderInput | Prisma.SortOrder
  dominantColor?: Prisma.SortOrderInput | Prisma.SortOrder
  filePath?: Prisma.SortOrder
  folderId?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.FilesCountOrderByAggregateInput
  _avg?: Prisma.FilesAvgOrderByAggregateInput
  _max?: Prisma.FilesMaxOrderByAggregateInput
  _min?: Prisma.FilesMinOrderByAggregateInput
  _sum?: Prisma.FilesSumOrderByAggregateInput
}

export type FilesScalarWhereWithAggregatesInput = {
  AND?: Prisma.FilesScalarWhereWithAggregatesInput | Prisma.FilesScalarWhereWithAggregatesInput[]
  OR?: Prisma.FilesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FilesScalarWhereWithAggregatesInput | Prisma.FilesScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Files"> | string
  originalname?: Prisma.StringWithAggregatesFilter<"Files"> | string
  extension?: Prisma.StringWithAggregatesFilter<"Files"> | string
  mimeType?: Prisma.StringWithAggregatesFilter<"Files"> | string
  size?: Prisma.IntWithAggregatesFilter<"Files"> | number
  width?: Prisma.IntNullableWithAggregatesFilter<"Files"> | number | null
  height?: Prisma.IntNullableWithAggregatesFilter<"Files"> | number | null
  checksum?: Prisma.StringNullableWithAggregatesFilter<"Files"> | string | null
  blurhash?: Prisma.StringNullableWithAggregatesFilter<"Files"> | string | null
  dominantColor?: Prisma.StringNullableWithAggregatesFilter<"Files"> | string | null
  filePath?: Prisma.StringWithAggregatesFilter<"Files"> | string
  folderId?: Prisma.StringNullableWithAggregatesFilter<"Files"> | string | null
  userId?: Prisma.StringWithAggregatesFilter<"Files"> | string
  isPublic?: Prisma.BoolWithAggregatesFilter<"Files"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Files"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Files"> | Date | string
}

export type FilesCreateInput = {
  id?: string
  originalname?: string
  extension?: string
  mimeType: string
  size: number
  width?: number | null
  height?: number | null
  checksum?: string | null
  blurhash?: string | null
  dominantColor?: string | null
  filePath: string
  isPublic?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  folder?: Prisma.FoldersCreateNestedOneWithoutFilesInput
  user: Prisma.UserCreateNestedOneWithoutFilesInput
  variants?: Prisma.FileVariantsCreateNestedManyWithoutFileInput
}

export type FilesUncheckedCreateInput = {
  id?: string
  originalname?: string
  extension?: string
  mimeType: string
  size: number
  width?: number | null
  height?: number | null
  checksum?: string | null
  blurhash?: string | null
  dominantColor?: string | null
  filePath: string
  folderId?: string | null
  userId: string
  isPublic?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  variants?: Prisma.FileVariantsUncheckedCreateNestedManyWithoutFileInput
}

export type FilesUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  originalname?: Prisma.StringFieldUpdateOperationsInput | string
  extension?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  size?: Prisma.IntFieldUpdateOperationsInput | number
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  blurhash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dominantColor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  filePath?: Prisma.StringFieldUpdateOperationsInput | string
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  folder?: Prisma.FoldersUpdateOneWithoutFilesNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutFilesNestedInput
  variants?: Prisma.FileVariantsUpdateManyWithoutFileNestedInput
}

export type FilesUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  originalname?: Prisma.StringFieldUpdateOperationsInput | string
  extension?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  size?: Prisma.IntFieldUpdateOperationsInput | number
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  blurhash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dominantColor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  filePath?: Prisma.StringFieldUpdateOperationsInput | string
  folderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  variants?: Prisma.FileVariantsUncheckedUpdateManyWithoutFileNestedInput
}

export type FilesCreateManyInput = {
  id?: string
  originalname?: string
  extension?: string
  mimeType: string
  size: number
  width?: number | null
  height?: number | null
  checksum?: string | null
  blurhash?: string | null
  dominantColor?: string | null
  filePath: string
  folderId?: string | null
  userId: string
  isPublic?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FilesUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  originalname?: Prisma.StringFieldUpdateOperationsInput | string
  extension?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  size?: Prisma.IntFieldUpdateOperationsInput | number
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  blurhash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dominantColor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  filePath?: Prisma.StringFieldUpdateOperationsInput | string
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FilesUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  originalname?: Prisma.StringFieldUpdateOperationsInput | string
  extension?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  size?: Prisma.IntFieldUpdateOperationsInput | number
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  blurhash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dominantColor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  filePath?: Prisma.StringFieldUpdateOperationsInput | string
  folderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FilesListRelationFilter = {
  every?: Prisma.FilesWhereInput
  some?: Prisma.FilesWhereInput
  none?: Prisma.FilesWhereInput
}

export type FilesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FilesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  originalname?: Prisma.SortOrder
  extension?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  size?: Prisma.SortOrder
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
  checksum?: Prisma.SortOrder
  blurhash?: Prisma.SortOrder
  dominantColor?: Prisma.SortOrder
  filePath?: Prisma.SortOrder
  folderId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FilesAvgOrderByAggregateInput = {
  size?: Prisma.SortOrder
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
}

export type FilesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  originalname?: Prisma.SortOrder
  extension?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  size?: Prisma.SortOrder
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
  checksum?: Prisma.SortOrder
  blurhash?: Prisma.SortOrder
  dominantColor?: Prisma.SortOrder
  filePath?: Prisma.SortOrder
  folderId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FilesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  originalname?: Prisma.SortOrder
  extension?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  size?: Prisma.SortOrder
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
  checksum?: Prisma.SortOrder
  blurhash?: Prisma.SortOrder
  dominantColor?: Prisma.SortOrder
  filePath?: Prisma.SortOrder
  folderId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FilesSumOrderByAggregateInput = {
  size?: Prisma.SortOrder
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
}

export type FilesScalarRelationFilter = {
  is?: Prisma.FilesWhereInput
  isNot?: Prisma.FilesWhereInput
}

export type FilesCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.FilesCreateWithoutUserInput, Prisma.FilesUncheckedCreateWithoutUserInput> | Prisma.FilesCreateWithoutUserInput[] | Prisma.FilesUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FilesCreateOrConnectWithoutUserInput | Prisma.FilesCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.FilesCreateManyUserInputEnvelope
  connect?: Prisma.FilesWhereUniqueInput | Prisma.FilesWhereUniqueInput[]
}

export type FilesUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.FilesCreateWithoutUserInput, Prisma.FilesUncheckedCreateWithoutUserInput> | Prisma.FilesCreateWithoutUserInput[] | Prisma.FilesUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FilesCreateOrConnectWithoutUserInput | Prisma.FilesCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.FilesCreateManyUserInputEnvelope
  connect?: Prisma.FilesWhereUniqueInput | Prisma.FilesWhereUniqueInput[]
}

export type FilesUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.FilesCreateWithoutUserInput, Prisma.FilesUncheckedCreateWithoutUserInput> | Prisma.FilesCreateWithoutUserInput[] | Prisma.FilesUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FilesCreateOrConnectWithoutUserInput | Prisma.FilesCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.FilesUpsertWithWhereUniqueWithoutUserInput | Prisma.FilesUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.FilesCreateManyUserInputEnvelope
  set?: Prisma.FilesWhereUniqueInput | Prisma.FilesWhereUniqueInput[]
  disconnect?: Prisma.FilesWhereUniqueInput | Prisma.FilesWhereUniqueInput[]
  delete?: Prisma.FilesWhereUniqueInput | Prisma.FilesWhereUniqueInput[]
  connect?: Prisma.FilesWhereUniqueInput | Prisma.FilesWhereUniqueInput[]
  update?: Prisma.FilesUpdateWithWhereUniqueWithoutUserInput | Prisma.FilesUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.FilesUpdateManyWithWhereWithoutUserInput | Prisma.FilesUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.FilesScalarWhereInput | Prisma.FilesScalarWhereInput[]
}

export type FilesUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.FilesCreateWithoutUserInput, Prisma.FilesUncheckedCreateWithoutUserInput> | Prisma.FilesCreateWithoutUserInput[] | Prisma.FilesUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FilesCreateOrConnectWithoutUserInput | Prisma.FilesCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.FilesUpsertWithWhereUniqueWithoutUserInput | Prisma.FilesUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.FilesCreateManyUserInputEnvelope
  set?: Prisma.FilesWhereUniqueInput | Prisma.FilesWhereUniqueInput[]
  disconnect?: Prisma.FilesWhereUniqueInput | Prisma.FilesWhereUniqueInput[]
  delete?: Prisma.FilesWhereUniqueInput | Prisma.FilesWhereUniqueInput[]
  connect?: Prisma.FilesWhereUniqueInput | Prisma.FilesWhereUniqueInput[]
  update?: Prisma.FilesUpdateWithWhereUniqueWithoutUserInput | Prisma.FilesUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.FilesUpdateManyWithWhereWithoutUserInput | Prisma.FilesUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.FilesScalarWhereInput | Prisma.FilesScalarWhereInput[]
}

export type FilesCreateNestedManyWithoutFolderInput = {
  create?: Prisma.XOR<Prisma.FilesCreateWithoutFolderInput, Prisma.FilesUncheckedCreateWithoutFolderInput> | Prisma.FilesCreateWithoutFolderInput[] | Prisma.FilesUncheckedCreateWithoutFolderInput[]
  connectOrCreate?: Prisma.FilesCreateOrConnectWithoutFolderInput | Prisma.FilesCreateOrConnectWithoutFolderInput[]
  createMany?: Prisma.FilesCreateManyFolderInputEnvelope
  connect?: Prisma.FilesWhereUniqueInput | Prisma.FilesWhereUniqueInput[]
}

export type FilesUncheckedCreateNestedManyWithoutFolderInput = {
  create?: Prisma.XOR<Prisma.FilesCreateWithoutFolderInput, Prisma.FilesUncheckedCreateWithoutFolderInput> | Prisma.FilesCreateWithoutFolderInput[] | Prisma.FilesUncheckedCreateWithoutFolderInput[]
  connectOrCreate?: Prisma.FilesCreateOrConnectWithoutFolderInput | Prisma.FilesCreateOrConnectWithoutFolderInput[]
  createMany?: Prisma.FilesCreateManyFolderInputEnvelope
  connect?: Prisma.FilesWhereUniqueInput | Prisma.FilesWhereUniqueInput[]
}

export type FilesUpdateManyWithoutFolderNestedInput = {
  create?: Prisma.XOR<Prisma.FilesCreateWithoutFolderInput, Prisma.FilesUncheckedCreateWithoutFolderInput> | Prisma.FilesCreateWithoutFolderInput[] | Prisma.FilesUncheckedCreateWithoutFolderInput[]
  connectOrCreate?: Prisma.FilesCreateOrConnectWithoutFolderInput | Prisma.FilesCreateOrConnectWithoutFolderInput[]
  upsert?: Prisma.FilesUpsertWithWhereUniqueWithoutFolderInput | Prisma.FilesUpsertWithWhereUniqueWithoutFolderInput[]
  createMany?: Prisma.FilesCreateManyFolderInputEnvelope
  set?: Prisma.FilesWhereUniqueInput | Prisma.FilesWhereUniqueInput[]
  disconnect?: Prisma.FilesWhereUniqueInput | Prisma.FilesWhereUniqueInput[]
  delete?: Prisma.FilesWhereUniqueInput | Prisma.FilesWhereUniqueInput[]
  connect?: Prisma.FilesWhereUniqueInput | Prisma.FilesWhereUniqueInput[]
  update?: Prisma.FilesUpdateWithWhereUniqueWithoutFolderInput | Prisma.FilesUpdateWithWhereUniqueWithoutFolderInput[]
  updateMany?: Prisma.FilesUpdateManyWithWhereWithoutFolderInput | Prisma.FilesUpdateManyWithWhereWithoutFolderInput[]
  deleteMany?: Prisma.FilesScalarWhereInput | Prisma.FilesScalarWhereInput[]
}

export type FilesUncheckedUpdateManyWithoutFolderNestedInput = {
  create?: Prisma.XOR<Prisma.FilesCreateWithoutFolderInput, Prisma.FilesUncheckedCreateWithoutFolderInput> | Prisma.FilesCreateWithoutFolderInput[] | Prisma.FilesUncheckedCreateWithoutFolderInput[]
  connectOrCreate?: Prisma.FilesCreateOrConnectWithoutFolderInput | Prisma.FilesCreateOrConnectWithoutFolderInput[]
  upsert?: Prisma.FilesUpsertWithWhereUniqueWithoutFolderInput | Prisma.FilesUpsertWithWhereUniqueWithoutFolderInput[]
  createMany?: Prisma.FilesCreateManyFolderInputEnvelope
  set?: Prisma.FilesWhereUniqueInput | Prisma.FilesWhereUniqueInput[]
  disconnect?: Prisma.FilesWhereUniqueInput | Prisma.FilesWhereUniqueInput[]
  delete?: Prisma.FilesWhereUniqueInput | Prisma.FilesWhereUniqueInput[]
  connect?: Prisma.FilesWhereUniqueInput | Prisma.FilesWhereUniqueInput[]
  update?: Prisma.FilesUpdateWithWhereUniqueWithoutFolderInput | Prisma.FilesUpdateWithWhereUniqueWithoutFolderInput[]
  updateMany?: Prisma.FilesUpdateManyWithWhereWithoutFolderInput | Prisma.FilesUpdateManyWithWhereWithoutFolderInput[]
  deleteMany?: Prisma.FilesScalarWhereInput | Prisma.FilesScalarWhereInput[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type FilesCreateNestedOneWithoutVariantsInput = {
  create?: Prisma.XOR<Prisma.FilesCreateWithoutVariantsInput, Prisma.FilesUncheckedCreateWithoutVariantsInput>
  connectOrCreate?: Prisma.FilesCreateOrConnectWithoutVariantsInput
  connect?: Prisma.FilesWhereUniqueInput
}

export type FilesUpdateOneRequiredWithoutVariantsNestedInput = {
  create?: Prisma.XOR<Prisma.FilesCreateWithoutVariantsInput, Prisma.FilesUncheckedCreateWithoutVariantsInput>
  connectOrCreate?: Prisma.FilesCreateOrConnectWithoutVariantsInput
  upsert?: Prisma.FilesUpsertWithoutVariantsInput
  connect?: Prisma.FilesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FilesUpdateToOneWithWhereWithoutVariantsInput, Prisma.FilesUpdateWithoutVariantsInput>, Prisma.FilesUncheckedUpdateWithoutVariantsInput>
}

export type FilesCreateWithoutUserInput = {
  id?: string
  originalname?: string
  extension?: string
  mimeType: string
  size: number
  width?: number | null
  height?: number | null
  checksum?: string | null
  blurhash?: string | null
  dominantColor?: string | null
  filePath: string
  isPublic?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  folder?: Prisma.FoldersCreateNestedOneWithoutFilesInput
  variants?: Prisma.FileVariantsCreateNestedManyWithoutFileInput
}

export type FilesUncheckedCreateWithoutUserInput = {
  id?: string
  originalname?: string
  extension?: string
  mimeType: string
  size: number
  width?: number | null
  height?: number | null
  checksum?: string | null
  blurhash?: string | null
  dominantColor?: string | null
  filePath: string
  folderId?: string | null
  isPublic?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  variants?: Prisma.FileVariantsUncheckedCreateNestedManyWithoutFileInput
}

export type FilesCreateOrConnectWithoutUserInput = {
  where: Prisma.FilesWhereUniqueInput
  create: Prisma.XOR<Prisma.FilesCreateWithoutUserInput, Prisma.FilesUncheckedCreateWithoutUserInput>
}

export type FilesCreateManyUserInputEnvelope = {
  data: Prisma.FilesCreateManyUserInput | Prisma.FilesCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type FilesUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.FilesWhereUniqueInput
  update: Prisma.XOR<Prisma.FilesUpdateWithoutUserInput, Prisma.FilesUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.FilesCreateWithoutUserInput, Prisma.FilesUncheckedCreateWithoutUserInput>
}

export type FilesUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.FilesWhereUniqueInput
  data: Prisma.XOR<Prisma.FilesUpdateWithoutUserInput, Prisma.FilesUncheckedUpdateWithoutUserInput>
}

export type FilesUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.FilesScalarWhereInput
  data: Prisma.XOR<Prisma.FilesUpdateManyMutationInput, Prisma.FilesUncheckedUpdateManyWithoutUserInput>
}

export type FilesScalarWhereInput = {
  AND?: Prisma.FilesScalarWhereInput | Prisma.FilesScalarWhereInput[]
  OR?: Prisma.FilesScalarWhereInput[]
  NOT?: Prisma.FilesScalarWhereInput | Prisma.FilesScalarWhereInput[]
  id?: Prisma.StringFilter<"Files"> | string
  originalname?: Prisma.StringFilter<"Files"> | string
  extension?: Prisma.StringFilter<"Files"> | string
  mimeType?: Prisma.StringFilter<"Files"> | string
  size?: Prisma.IntFilter<"Files"> | number
  width?: Prisma.IntNullableFilter<"Files"> | number | null
  height?: Prisma.IntNullableFilter<"Files"> | number | null
  checksum?: Prisma.StringNullableFilter<"Files"> | string | null
  blurhash?: Prisma.StringNullableFilter<"Files"> | string | null
  dominantColor?: Prisma.StringNullableFilter<"Files"> | string | null
  filePath?: Prisma.StringFilter<"Files"> | string
  folderId?: Prisma.StringNullableFilter<"Files"> | string | null
  userId?: Prisma.StringFilter<"Files"> | string
  isPublic?: Prisma.BoolFilter<"Files"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Files"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Files"> | Date | string
}

export type FilesCreateWithoutFolderInput = {
  id?: string
  originalname?: string
  extension?: string
  mimeType: string
  size: number
  width?: number | null
  height?: number | null
  checksum?: string | null
  blurhash?: string | null
  dominantColor?: string | null
  filePath: string
  isPublic?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutFilesInput
  variants?: Prisma.FileVariantsCreateNestedManyWithoutFileInput
}

export type FilesUncheckedCreateWithoutFolderInput = {
  id?: string
  originalname?: string
  extension?: string
  mimeType: string
  size: number
  width?: number | null
  height?: number | null
  checksum?: string | null
  blurhash?: string | null
  dominantColor?: string | null
  filePath: string
  userId: string
  isPublic?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  variants?: Prisma.FileVariantsUncheckedCreateNestedManyWithoutFileInput
}

export type FilesCreateOrConnectWithoutFolderInput = {
  where: Prisma.FilesWhereUniqueInput
  create: Prisma.XOR<Prisma.FilesCreateWithoutFolderInput, Prisma.FilesUncheckedCreateWithoutFolderInput>
}

export type FilesCreateManyFolderInputEnvelope = {
  data: Prisma.FilesCreateManyFolderInput | Prisma.FilesCreateManyFolderInput[]
  skipDuplicates?: boolean
}

export type FilesUpsertWithWhereUniqueWithoutFolderInput = {
  where: Prisma.FilesWhereUniqueInput
  update: Prisma.XOR<Prisma.FilesUpdateWithoutFolderInput, Prisma.FilesUncheckedUpdateWithoutFolderInput>
  create: Prisma.XOR<Prisma.FilesCreateWithoutFolderInput, Prisma.FilesUncheckedCreateWithoutFolderInput>
}

export type FilesUpdateWithWhereUniqueWithoutFolderInput = {
  where: Prisma.FilesWhereUniqueInput
  data: Prisma.XOR<Prisma.FilesUpdateWithoutFolderInput, Prisma.FilesUncheckedUpdateWithoutFolderInput>
}

export type FilesUpdateManyWithWhereWithoutFolderInput = {
  where: Prisma.FilesScalarWhereInput
  data: Prisma.XOR<Prisma.FilesUpdateManyMutationInput, Prisma.FilesUncheckedUpdateManyWithoutFolderInput>
}

export type FilesCreateWithoutVariantsInput = {
  id?: string
  originalname?: string
  extension?: string
  mimeType: string
  size: number
  width?: number | null
  height?: number | null
  checksum?: string | null
  blurhash?: string | null
  dominantColor?: string | null
  filePath: string
  isPublic?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  folder?: Prisma.FoldersCreateNestedOneWithoutFilesInput
  user: Prisma.UserCreateNestedOneWithoutFilesInput
}

export type FilesUncheckedCreateWithoutVariantsInput = {
  id?: string
  originalname?: string
  extension?: string
  mimeType: string
  size: number
  width?: number | null
  height?: number | null
  checksum?: string | null
  blurhash?: string | null
  dominantColor?: string | null
  filePath: string
  folderId?: string | null
  userId: string
  isPublic?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FilesCreateOrConnectWithoutVariantsInput = {
  where: Prisma.FilesWhereUniqueInput
  create: Prisma.XOR<Prisma.FilesCreateWithoutVariantsInput, Prisma.FilesUncheckedCreateWithoutVariantsInput>
}

export type FilesUpsertWithoutVariantsInput = {
  update: Prisma.XOR<Prisma.FilesUpdateWithoutVariantsInput, Prisma.FilesUncheckedUpdateWithoutVariantsInput>
  create: Prisma.XOR<Prisma.FilesCreateWithoutVariantsInput, Prisma.FilesUncheckedCreateWithoutVariantsInput>
  where?: Prisma.FilesWhereInput
}

export type FilesUpdateToOneWithWhereWithoutVariantsInput = {
  where?: Prisma.FilesWhereInput
  data: Prisma.XOR<Prisma.FilesUpdateWithoutVariantsInput, Prisma.FilesUncheckedUpdateWithoutVariantsInput>
}

export type FilesUpdateWithoutVariantsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  originalname?: Prisma.StringFieldUpdateOperationsInput | string
  extension?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  size?: Prisma.IntFieldUpdateOperationsInput | number
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  blurhash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dominantColor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  filePath?: Prisma.StringFieldUpdateOperationsInput | string
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  folder?: Prisma.FoldersUpdateOneWithoutFilesNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutFilesNestedInput
}

export type FilesUncheckedUpdateWithoutVariantsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  originalname?: Prisma.StringFieldUpdateOperationsInput | string
  extension?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  size?: Prisma.IntFieldUpdateOperationsInput | number
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  blurhash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dominantColor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  filePath?: Prisma.StringFieldUpdateOperationsInput | string
  folderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FilesCreateManyUserInput = {
  id?: string
  originalname?: string
  extension?: string
  mimeType: string
  size: number
  width?: number | null
  height?: number | null
  checksum?: string | null
  blurhash?: string | null
  dominantColor?: string | null
  filePath: string
  folderId?: string | null
  isPublic?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FilesUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  originalname?: Prisma.StringFieldUpdateOperationsInput | string
  extension?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  size?: Prisma.IntFieldUpdateOperationsInput | number
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  blurhash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dominantColor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  filePath?: Prisma.StringFieldUpdateOperationsInput | string
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  folder?: Prisma.FoldersUpdateOneWithoutFilesNestedInput
  variants?: Prisma.FileVariantsUpdateManyWithoutFileNestedInput
}

export type FilesUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  originalname?: Prisma.StringFieldUpdateOperationsInput | string
  extension?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  size?: Prisma.IntFieldUpdateOperationsInput | number
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  blurhash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dominantColor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  filePath?: Prisma.StringFieldUpdateOperationsInput | string
  folderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  variants?: Prisma.FileVariantsUncheckedUpdateManyWithoutFileNestedInput
}

export type FilesUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  originalname?: Prisma.StringFieldUpdateOperationsInput | string
  extension?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  size?: Prisma.IntFieldUpdateOperationsInput | number
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  blurhash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dominantColor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  filePath?: Prisma.StringFieldUpdateOperationsInput | string
  folderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FilesCreateManyFolderInput = {
  id?: string
  originalname?: string
  extension?: string
  mimeType: string
  size: number
  width?: number | null
  height?: number | null
  checksum?: string | null
  blurhash?: string | null
  dominantColor?: string | null
  filePath: string
  userId: string
  isPublic?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FilesUpdateWithoutFolderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  originalname?: Prisma.StringFieldUpdateOperationsInput | string
  extension?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  size?: Prisma.IntFieldUpdateOperationsInput | number
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  blurhash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dominantColor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  filePath?: Prisma.StringFieldUpdateOperationsInput | string
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutFilesNestedInput
  variants?: Prisma.FileVariantsUpdateManyWithoutFileNestedInput
}

export type FilesUncheckedUpdateWithoutFolderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  originalname?: Prisma.StringFieldUpdateOperationsInput | string
  extension?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  size?: Prisma.IntFieldUpdateOperationsInput | number
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  blurhash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dominantColor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  filePath?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  variants?: Prisma.FileVariantsUncheckedUpdateManyWithoutFileNestedInput
}

export type FilesUncheckedUpdateManyWithoutFolderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  originalname?: Prisma.StringFieldUpdateOperationsInput | string
  extension?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.StringFieldUpdateOperationsInput | string
  size?: Prisma.IntFieldUpdateOperationsInput | number
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  checksum?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  blurhash?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dominantColor?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  filePath?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type FilesCountOutputType
 */

export type FilesCountOutputType = {
  variants: number
}

export type FilesCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  variants?: boolean | FilesCountOutputTypeCountVariantsArgs
}

/**
 * FilesCountOutputType without action
 */
export type FilesCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilesCountOutputType
   */
  select?: Prisma.FilesCountOutputTypeSelect<ExtArgs> | null
}

/**
 * FilesCountOutputType without action
 */
export type FilesCountOutputTypeCountVariantsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FileVariantsWhereInput
}


export type FilesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  originalname?: boolean
  extension?: boolean
  mimeType?: boolean
  size?: boolean
  width?: boolean
  height?: boolean
  checksum?: boolean
  blurhash?: boolean
  dominantColor?: boolean
  filePath?: boolean
  folderId?: boolean
  userId?: boolean
  isPublic?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  folder?: boolean | Prisma.Files$folderArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  variants?: boolean | Prisma.Files$variantsArgs<ExtArgs>
  _count?: boolean | Prisma.FilesCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["files"]>

export type FilesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  originalname?: boolean
  extension?: boolean
  mimeType?: boolean
  size?: boolean
  width?: boolean
  height?: boolean
  checksum?: boolean
  blurhash?: boolean
  dominantColor?: boolean
  filePath?: boolean
  folderId?: boolean
  userId?: boolean
  isPublic?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  folder?: boolean | Prisma.Files$folderArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["files"]>

export type FilesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  originalname?: boolean
  extension?: boolean
  mimeType?: boolean
  size?: boolean
  width?: boolean
  height?: boolean
  checksum?: boolean
  blurhash?: boolean
  dominantColor?: boolean
  filePath?: boolean
  folderId?: boolean
  userId?: boolean
  isPublic?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  folder?: boolean | Prisma.Files$folderArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["files"]>

export type FilesSelectScalar = {
  id?: boolean
  originalname?: boolean
  extension?: boolean
  mimeType?: boolean
  size?: boolean
  width?: boolean
  height?: boolean
  checksum?: boolean
  blurhash?: boolean
  dominantColor?: boolean
  filePath?: boolean
  folderId?: boolean
  userId?: boolean
  isPublic?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type FilesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "originalname" | "extension" | "mimeType" | "size" | "width" | "height" | "checksum" | "blurhash" | "dominantColor" | "filePath" | "folderId" | "userId" | "isPublic" | "createdAt" | "updatedAt", ExtArgs["result"]["files"]>
export type FilesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  folder?: boolean | Prisma.Files$folderArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  variants?: boolean | Prisma.Files$variantsArgs<ExtArgs>
  _count?: boolean | Prisma.FilesCountOutputTypeDefaultArgs<ExtArgs>
}
export type FilesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  folder?: boolean | Prisma.Files$folderArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type FilesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  folder?: boolean | Prisma.Files$folderArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $FilesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Files"
  objects: {
    folder: Prisma.$FoldersPayload<ExtArgs> | null
    user: Prisma.$UserPayload<ExtArgs>
    variants: Prisma.$FileVariantsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    originalname: string
    extension: string
    mimeType: string
    size: number
    width: number | null
    height: number | null
    checksum: string | null
    blurhash: string | null
    dominantColor: string | null
    filePath: string
    folderId: string | null
    userId: string
    isPublic: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["files"]>
  composites: {}
}

export type FilesGetPayload<S extends boolean | null | undefined | FilesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FilesPayload, S>

export type FilesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FilesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FilesCountAggregateInputType | true
  }

export interface FilesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Files'], meta: { name: 'Files' } }
  /**
   * Find zero or one Files that matches the filter.
   * @param {FilesFindUniqueArgs} args - Arguments to find a Files
   * @example
   * // Get one Files
   * const files = await prisma.files.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FilesFindUniqueArgs>(args: Prisma.SelectSubset<T, FilesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FilesClient<runtime.Types.Result.GetResult<Prisma.$FilesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Files that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FilesFindUniqueOrThrowArgs} args - Arguments to find a Files
   * @example
   * // Get one Files
   * const files = await prisma.files.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FilesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FilesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FilesClient<runtime.Types.Result.GetResult<Prisma.$FilesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Files that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilesFindFirstArgs} args - Arguments to find a Files
   * @example
   * // Get one Files
   * const files = await prisma.files.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FilesFindFirstArgs>(args?: Prisma.SelectSubset<T, FilesFindFirstArgs<ExtArgs>>): Prisma.Prisma__FilesClient<runtime.Types.Result.GetResult<Prisma.$FilesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Files that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilesFindFirstOrThrowArgs} args - Arguments to find a Files
   * @example
   * // Get one Files
   * const files = await prisma.files.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FilesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FilesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FilesClient<runtime.Types.Result.GetResult<Prisma.$FilesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Files that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Files
   * const files = await prisma.files.findMany()
   * 
   * // Get first 10 Files
   * const files = await prisma.files.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const filesWithIdOnly = await prisma.files.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FilesFindManyArgs>(args?: Prisma.SelectSubset<T, FilesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FilesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Files.
   * @param {FilesCreateArgs} args - Arguments to create a Files.
   * @example
   * // Create one Files
   * const Files = await prisma.files.create({
   *   data: {
   *     // ... data to create a Files
   *   }
   * })
   * 
   */
  create<T extends FilesCreateArgs>(args: Prisma.SelectSubset<T, FilesCreateArgs<ExtArgs>>): Prisma.Prisma__FilesClient<runtime.Types.Result.GetResult<Prisma.$FilesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Files.
   * @param {FilesCreateManyArgs} args - Arguments to create many Files.
   * @example
   * // Create many Files
   * const files = await prisma.files.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FilesCreateManyArgs>(args?: Prisma.SelectSubset<T, FilesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Files and returns the data saved in the database.
   * @param {FilesCreateManyAndReturnArgs} args - Arguments to create many Files.
   * @example
   * // Create many Files
   * const files = await prisma.files.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Files and only return the `id`
   * const filesWithIdOnly = await prisma.files.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FilesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FilesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FilesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Files.
   * @param {FilesDeleteArgs} args - Arguments to delete one Files.
   * @example
   * // Delete one Files
   * const Files = await prisma.files.delete({
   *   where: {
   *     // ... filter to delete one Files
   *   }
   * })
   * 
   */
  delete<T extends FilesDeleteArgs>(args: Prisma.SelectSubset<T, FilesDeleteArgs<ExtArgs>>): Prisma.Prisma__FilesClient<runtime.Types.Result.GetResult<Prisma.$FilesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Files.
   * @param {FilesUpdateArgs} args - Arguments to update one Files.
   * @example
   * // Update one Files
   * const files = await prisma.files.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FilesUpdateArgs>(args: Prisma.SelectSubset<T, FilesUpdateArgs<ExtArgs>>): Prisma.Prisma__FilesClient<runtime.Types.Result.GetResult<Prisma.$FilesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Files.
   * @param {FilesDeleteManyArgs} args - Arguments to filter Files to delete.
   * @example
   * // Delete a few Files
   * const { count } = await prisma.files.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FilesDeleteManyArgs>(args?: Prisma.SelectSubset<T, FilesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Files.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Files
   * const files = await prisma.files.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FilesUpdateManyArgs>(args: Prisma.SelectSubset<T, FilesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Files and returns the data updated in the database.
   * @param {FilesUpdateManyAndReturnArgs} args - Arguments to update many Files.
   * @example
   * // Update many Files
   * const files = await prisma.files.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Files and only return the `id`
   * const filesWithIdOnly = await prisma.files.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FilesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FilesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FilesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Files.
   * @param {FilesUpsertArgs} args - Arguments to update or create a Files.
   * @example
   * // Update or create a Files
   * const files = await prisma.files.upsert({
   *   create: {
   *     // ... data to create a Files
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Files we want to update
   *   }
   * })
   */
  upsert<T extends FilesUpsertArgs>(args: Prisma.SelectSubset<T, FilesUpsertArgs<ExtArgs>>): Prisma.Prisma__FilesClient<runtime.Types.Result.GetResult<Prisma.$FilesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Files.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilesCountArgs} args - Arguments to filter Files to count.
   * @example
   * // Count the number of Files
   * const count = await prisma.files.count({
   *   where: {
   *     // ... the filter for the Files we want to count
   *   }
   * })
  **/
  count<T extends FilesCountArgs>(
    args?: Prisma.Subset<T, FilesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FilesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Files.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FilesAggregateArgs>(args: Prisma.Subset<T, FilesAggregateArgs>): Prisma.PrismaPromise<GetFilesAggregateType<T>>

  /**
   * Group by Files.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FilesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FilesGroupByArgs['orderBy'] }
      : { orderBy?: FilesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FilesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFilesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Files model
 */
readonly fields: FilesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Files.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FilesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  folder<T extends Prisma.Files$folderArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Files$folderArgs<ExtArgs>>): Prisma.Prisma__FoldersClient<runtime.Types.Result.GetResult<Prisma.$FoldersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  variants<T extends Prisma.Files$variantsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Files$variantsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FileVariantsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Files model
 */
export interface FilesFieldRefs {
  readonly id: Prisma.FieldRef<"Files", 'String'>
  readonly originalname: Prisma.FieldRef<"Files", 'String'>
  readonly extension: Prisma.FieldRef<"Files", 'String'>
  readonly mimeType: Prisma.FieldRef<"Files", 'String'>
  readonly size: Prisma.FieldRef<"Files", 'Int'>
  readonly width: Prisma.FieldRef<"Files", 'Int'>
  readonly height: Prisma.FieldRef<"Files", 'Int'>
  readonly checksum: Prisma.FieldRef<"Files", 'String'>
  readonly blurhash: Prisma.FieldRef<"Files", 'String'>
  readonly dominantColor: Prisma.FieldRef<"Files", 'String'>
  readonly filePath: Prisma.FieldRef<"Files", 'String'>
  readonly folderId: Prisma.FieldRef<"Files", 'String'>
  readonly userId: Prisma.FieldRef<"Files", 'String'>
  readonly isPublic: Prisma.FieldRef<"Files", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"Files", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Files", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Files findUnique
 */
export type FilesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Files
   */
  select?: Prisma.FilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Files
   */
  omit?: Prisma.FilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesInclude<ExtArgs> | null
  /**
   * Filter, which Files to fetch.
   */
  where: Prisma.FilesWhereUniqueInput
}

/**
 * Files findUniqueOrThrow
 */
export type FilesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Files
   */
  select?: Prisma.FilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Files
   */
  omit?: Prisma.FilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesInclude<ExtArgs> | null
  /**
   * Filter, which Files to fetch.
   */
  where: Prisma.FilesWhereUniqueInput
}

/**
 * Files findFirst
 */
export type FilesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Files
   */
  select?: Prisma.FilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Files
   */
  omit?: Prisma.FilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesInclude<ExtArgs> | null
  /**
   * Filter, which Files to fetch.
   */
  where?: Prisma.FilesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Files to fetch.
   */
  orderBy?: Prisma.FilesOrderByWithRelationInput | Prisma.FilesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Files.
   */
  cursor?: Prisma.FilesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Files from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Files.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Files.
   */
  distinct?: Prisma.FilesScalarFieldEnum | Prisma.FilesScalarFieldEnum[]
}

/**
 * Files findFirstOrThrow
 */
export type FilesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Files
   */
  select?: Prisma.FilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Files
   */
  omit?: Prisma.FilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesInclude<ExtArgs> | null
  /**
   * Filter, which Files to fetch.
   */
  where?: Prisma.FilesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Files to fetch.
   */
  orderBy?: Prisma.FilesOrderByWithRelationInput | Prisma.FilesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Files.
   */
  cursor?: Prisma.FilesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Files from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Files.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Files.
   */
  distinct?: Prisma.FilesScalarFieldEnum | Prisma.FilesScalarFieldEnum[]
}

/**
 * Files findMany
 */
export type FilesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Files
   */
  select?: Prisma.FilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Files
   */
  omit?: Prisma.FilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesInclude<ExtArgs> | null
  /**
   * Filter, which Files to fetch.
   */
  where?: Prisma.FilesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Files to fetch.
   */
  orderBy?: Prisma.FilesOrderByWithRelationInput | Prisma.FilesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Files.
   */
  cursor?: Prisma.FilesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Files from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Files.
   */
  skip?: number
  distinct?: Prisma.FilesScalarFieldEnum | Prisma.FilesScalarFieldEnum[]
}

/**
 * Files create
 */
export type FilesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Files
   */
  select?: Prisma.FilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Files
   */
  omit?: Prisma.FilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesInclude<ExtArgs> | null
  /**
   * The data needed to create a Files.
   */
  data: Prisma.XOR<Prisma.FilesCreateInput, Prisma.FilesUncheckedCreateInput>
}

/**
 * Files createMany
 */
export type FilesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Files.
   */
  data: Prisma.FilesCreateManyInput | Prisma.FilesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Files createManyAndReturn
 */
export type FilesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Files
   */
  select?: Prisma.FilesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Files
   */
  omit?: Prisma.FilesOmit<ExtArgs> | null
  /**
   * The data used to create many Files.
   */
  data: Prisma.FilesCreateManyInput | Prisma.FilesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Files update
 */
export type FilesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Files
   */
  select?: Prisma.FilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Files
   */
  omit?: Prisma.FilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesInclude<ExtArgs> | null
  /**
   * The data needed to update a Files.
   */
  data: Prisma.XOR<Prisma.FilesUpdateInput, Prisma.FilesUncheckedUpdateInput>
  /**
   * Choose, which Files to update.
   */
  where: Prisma.FilesWhereUniqueInput
}

/**
 * Files updateMany
 */
export type FilesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Files.
   */
  data: Prisma.XOR<Prisma.FilesUpdateManyMutationInput, Prisma.FilesUncheckedUpdateManyInput>
  /**
   * Filter which Files to update
   */
  where?: Prisma.FilesWhereInput
  /**
   * Limit how many Files to update.
   */
  limit?: number
}

/**
 * Files updateManyAndReturn
 */
export type FilesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Files
   */
  select?: Prisma.FilesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Files
   */
  omit?: Prisma.FilesOmit<ExtArgs> | null
  /**
   * The data used to update Files.
   */
  data: Prisma.XOR<Prisma.FilesUpdateManyMutationInput, Prisma.FilesUncheckedUpdateManyInput>
  /**
   * Filter which Files to update
   */
  where?: Prisma.FilesWhereInput
  /**
   * Limit how many Files to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Files upsert
 */
export type FilesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Files
   */
  select?: Prisma.FilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Files
   */
  omit?: Prisma.FilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesInclude<ExtArgs> | null
  /**
   * The filter to search for the Files to update in case it exists.
   */
  where: Prisma.FilesWhereUniqueInput
  /**
   * In case the Files found by the `where` argument doesn't exist, create a new Files with this data.
   */
  create: Prisma.XOR<Prisma.FilesCreateInput, Prisma.FilesUncheckedCreateInput>
  /**
   * In case the Files was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FilesUpdateInput, Prisma.FilesUncheckedUpdateInput>
}

/**
 * Files delete
 */
export type FilesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Files
   */
  select?: Prisma.FilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Files
   */
  omit?: Prisma.FilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesInclude<ExtArgs> | null
  /**
   * Filter which Files to delete.
   */
  where: Prisma.FilesWhereUniqueInput
}

/**
 * Files deleteMany
 */
export type FilesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Files to delete
   */
  where?: Prisma.FilesWhereInput
  /**
   * Limit how many Files to delete.
   */
  limit?: number
}

/**
 * Files.folder
 */
export type Files$folderArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folders
   */
  select?: Prisma.FoldersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Folders
   */
  omit?: Prisma.FoldersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FoldersInclude<ExtArgs> | null
  where?: Prisma.FoldersWhereInput
}

/**
 * Files.variants
 */
export type Files$variantsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileVariants
   */
  select?: Prisma.FileVariantsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileVariants
   */
  omit?: Prisma.FileVariantsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileVariantsInclude<ExtArgs> | null
  where?: Prisma.FileVariantsWhereInput
  orderBy?: Prisma.FileVariantsOrderByWithRelationInput | Prisma.FileVariantsOrderByWithRelationInput[]
  cursor?: Prisma.FileVariantsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FileVariantsScalarFieldEnum | Prisma.FileVariantsScalarFieldEnum[]
}

/**
 * Files without action
 */
export type FilesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Files
   */
  select?: Prisma.FilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Files
   */
  omit?: Prisma.FilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesInclude<ExtArgs> | null
}
