
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FileVariants` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model FileVariants
 * 
 */
export type FileVariantsModel = runtime.Types.Result.DefaultSelection<Prisma.$FileVariantsPayload>

export type AggregateFileVariants = {
  _count: FileVariantsCountAggregateOutputType | null
  _avg: FileVariantsAvgAggregateOutputType | null
  _sum: FileVariantsSumAggregateOutputType | null
  _min: FileVariantsMinAggregateOutputType | null
  _max: FileVariantsMaxAggregateOutputType | null
}

export type FileVariantsAvgAggregateOutputType = {
  width: number | null
  height: number | null
  size: number | null
}

export type FileVariantsSumAggregateOutputType = {
  width: number | null
  height: number | null
  size: number | null
}

export type FileVariantsMinAggregateOutputType = {
  id: string | null
  fileId: string | null
  type: $Enums.VariantType | null
  storageKey: string | null
  format: string | null
  width: number | null
  height: number | null
  size: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FileVariantsMaxAggregateOutputType = {
  id: string | null
  fileId: string | null
  type: $Enums.VariantType | null
  storageKey: string | null
  format: string | null
  width: number | null
  height: number | null
  size: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FileVariantsCountAggregateOutputType = {
  id: number
  fileId: number
  type: number
  storageKey: number
  format: number
  width: number
  height: number
  size: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type FileVariantsAvgAggregateInputType = {
  width?: true
  height?: true
  size?: true
}

export type FileVariantsSumAggregateInputType = {
  width?: true
  height?: true
  size?: true
}

export type FileVariantsMinAggregateInputType = {
  id?: true
  fileId?: true
  type?: true
  storageKey?: true
  format?: true
  width?: true
  height?: true
  size?: true
  createdAt?: true
  updatedAt?: true
}

export type FileVariantsMaxAggregateInputType = {
  id?: true
  fileId?: true
  type?: true
  storageKey?: true
  format?: true
  width?: true
  height?: true
  size?: true
  createdAt?: true
  updatedAt?: true
}

export type FileVariantsCountAggregateInputType = {
  id?: true
  fileId?: true
  type?: true
  storageKey?: true
  format?: true
  width?: true
  height?: true
  size?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type FileVariantsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FileVariants to aggregate.
   */
  where?: Prisma.FileVariantsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FileVariants to fetch.
   */
  orderBy?: Prisma.FileVariantsOrderByWithRelationInput | Prisma.FileVariantsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FileVariantsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FileVariants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FileVariants.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FileVariants
  **/
  _count?: true | FileVariantsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: FileVariantsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: FileVariantsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FileVariantsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FileVariantsMaxAggregateInputType
}

export type GetFileVariantsAggregateType<T extends FileVariantsAggregateArgs> = {
      [P in keyof T & keyof AggregateFileVariants]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFileVariants[P]>
    : Prisma.GetScalarType<T[P], AggregateFileVariants[P]>
}




export type FileVariantsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FileVariantsWhereInput
  orderBy?: Prisma.FileVariantsOrderByWithAggregationInput | Prisma.FileVariantsOrderByWithAggregationInput[]
  by: Prisma.FileVariantsScalarFieldEnum[] | Prisma.FileVariantsScalarFieldEnum
  having?: Prisma.FileVariantsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FileVariantsCountAggregateInputType | true
  _avg?: FileVariantsAvgAggregateInputType
  _sum?: FileVariantsSumAggregateInputType
  _min?: FileVariantsMinAggregateInputType
  _max?: FileVariantsMaxAggregateInputType
}

export type FileVariantsGroupByOutputType = {
  id: string
  fileId: string
  type: $Enums.VariantType
  storageKey: string
  format: string
  width: number | null
  height: number | null
  size: number
  createdAt: Date
  updatedAt: Date
  _count: FileVariantsCountAggregateOutputType | null
  _avg: FileVariantsAvgAggregateOutputType | null
  _sum: FileVariantsSumAggregateOutputType | null
  _min: FileVariantsMinAggregateOutputType | null
  _max: FileVariantsMaxAggregateOutputType | null
}

type GetFileVariantsGroupByPayload<T extends FileVariantsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FileVariantsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FileVariantsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FileVariantsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FileVariantsGroupByOutputType[P]>
      }
    >
  >



export type FileVariantsWhereInput = {
  AND?: Prisma.FileVariantsWhereInput | Prisma.FileVariantsWhereInput[]
  OR?: Prisma.FileVariantsWhereInput[]
  NOT?: Prisma.FileVariantsWhereInput | Prisma.FileVariantsWhereInput[]
  id?: Prisma.StringFilter<"FileVariants"> | string
  fileId?: Prisma.StringFilter<"FileVariants"> | string
  type?: Prisma.EnumVariantTypeFilter<"FileVariants"> | $Enums.VariantType
  storageKey?: Prisma.StringFilter<"FileVariants"> | string
  format?: Prisma.StringFilter<"FileVariants"> | string
  width?: Prisma.IntNullableFilter<"FileVariants"> | number | null
  height?: Prisma.IntNullableFilter<"FileVariants"> | number | null
  size?: Prisma.IntFilter<"FileVariants"> | number
  createdAt?: Prisma.DateTimeFilter<"FileVariants"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FileVariants"> | Date | string
  file?: Prisma.XOR<Prisma.FilesScalarRelationFilter, Prisma.FilesWhereInput>
}

export type FileVariantsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  fileId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  storageKey?: Prisma.SortOrder
  format?: Prisma.SortOrder
  width?: Prisma.SortOrderInput | Prisma.SortOrder
  height?: Prisma.SortOrderInput | Prisma.SortOrder
  size?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  file?: Prisma.FilesOrderByWithRelationInput
}

export type FileVariantsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  storageKey?: string
  AND?: Prisma.FileVariantsWhereInput | Prisma.FileVariantsWhereInput[]
  OR?: Prisma.FileVariantsWhereInput[]
  NOT?: Prisma.FileVariantsWhereInput | Prisma.FileVariantsWhereInput[]
  fileId?: Prisma.StringFilter<"FileVariants"> | string
  type?: Prisma.EnumVariantTypeFilter<"FileVariants"> | $Enums.VariantType
  format?: Prisma.StringFilter<"FileVariants"> | string
  width?: Prisma.IntNullableFilter<"FileVariants"> | number | null
  height?: Prisma.IntNullableFilter<"FileVariants"> | number | null
  size?: Prisma.IntFilter<"FileVariants"> | number
  createdAt?: Prisma.DateTimeFilter<"FileVariants"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FileVariants"> | Date | string
  file?: Prisma.XOR<Prisma.FilesScalarRelationFilter, Prisma.FilesWhereInput>
}, "id" | "storageKey">

export type FileVariantsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  fileId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  storageKey?: Prisma.SortOrder
  format?: Prisma.SortOrder
  width?: Prisma.SortOrderInput | Prisma.SortOrder
  height?: Prisma.SortOrderInput | Prisma.SortOrder
  size?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.FileVariantsCountOrderByAggregateInput
  _avg?: Prisma.FileVariantsAvgOrderByAggregateInput
  _max?: Prisma.FileVariantsMaxOrderByAggregateInput
  _min?: Prisma.FileVariantsMinOrderByAggregateInput
  _sum?: Prisma.FileVariantsSumOrderByAggregateInput
}

export type FileVariantsScalarWhereWithAggregatesInput = {
  AND?: Prisma.FileVariantsScalarWhereWithAggregatesInput | Prisma.FileVariantsScalarWhereWithAggregatesInput[]
  OR?: Prisma.FileVariantsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FileVariantsScalarWhereWithAggregatesInput | Prisma.FileVariantsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FileVariants"> | string
  fileId?: Prisma.StringWithAggregatesFilter<"FileVariants"> | string
  type?: Prisma.EnumVariantTypeWithAggregatesFilter<"FileVariants"> | $Enums.VariantType
  storageKey?: Prisma.StringWithAggregatesFilter<"FileVariants"> | string
  format?: Prisma.StringWithAggregatesFilter<"FileVariants"> | string
  width?: Prisma.IntNullableWithAggregatesFilter<"FileVariants"> | number | null
  height?: Prisma.IntNullableWithAggregatesFilter<"FileVariants"> | number | null
  size?: Prisma.IntWithAggregatesFilter<"FileVariants"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"FileVariants"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"FileVariants"> | Date | string
}

export type FileVariantsCreateInput = {
  id?: string
  type: $Enums.VariantType
  storageKey: string
  format: string
  width?: number | null
  height?: number | null
  size: number
  createdAt?: Date | string
  updatedAt?: Date | string
  file: Prisma.FilesCreateNestedOneWithoutVariantsInput
}

export type FileVariantsUncheckedCreateInput = {
  id?: string
  fileId: string
  type: $Enums.VariantType
  storageKey: string
  format: string
  width?: number | null
  height?: number | null
  size: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FileVariantsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumVariantTypeFieldUpdateOperationsInput | $Enums.VariantType
  storageKey?: Prisma.StringFieldUpdateOperationsInput | string
  format?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  size?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  file?: Prisma.FilesUpdateOneRequiredWithoutVariantsNestedInput
}

export type FileVariantsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumVariantTypeFieldUpdateOperationsInput | $Enums.VariantType
  storageKey?: Prisma.StringFieldUpdateOperationsInput | string
  format?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  size?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FileVariantsCreateManyInput = {
  id?: string
  fileId: string
  type: $Enums.VariantType
  storageKey: string
  format: string
  width?: number | null
  height?: number | null
  size: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FileVariantsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumVariantTypeFieldUpdateOperationsInput | $Enums.VariantType
  storageKey?: Prisma.StringFieldUpdateOperationsInput | string
  format?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  size?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FileVariantsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumVariantTypeFieldUpdateOperationsInput | $Enums.VariantType
  storageKey?: Prisma.StringFieldUpdateOperationsInput | string
  format?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  size?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FileVariantsListRelationFilter = {
  every?: Prisma.FileVariantsWhereInput
  some?: Prisma.FileVariantsWhereInput
  none?: Prisma.FileVariantsWhereInput
}

export type FileVariantsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FileVariantsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fileId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  storageKey?: Prisma.SortOrder
  format?: Prisma.SortOrder
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
  size?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FileVariantsAvgOrderByAggregateInput = {
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
  size?: Prisma.SortOrder
}

export type FileVariantsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fileId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  storageKey?: Prisma.SortOrder
  format?: Prisma.SortOrder
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
  size?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FileVariantsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fileId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  storageKey?: Prisma.SortOrder
  format?: Prisma.SortOrder
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
  size?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FileVariantsSumOrderByAggregateInput = {
  width?: Prisma.SortOrder
  height?: Prisma.SortOrder
  size?: Prisma.SortOrder
}

export type FileVariantsCreateNestedManyWithoutFileInput = {
  create?: Prisma.XOR<Prisma.FileVariantsCreateWithoutFileInput, Prisma.FileVariantsUncheckedCreateWithoutFileInput> | Prisma.FileVariantsCreateWithoutFileInput[] | Prisma.FileVariantsUncheckedCreateWithoutFileInput[]
  connectOrCreate?: Prisma.FileVariantsCreateOrConnectWithoutFileInput | Prisma.FileVariantsCreateOrConnectWithoutFileInput[]
  createMany?: Prisma.FileVariantsCreateManyFileInputEnvelope
  connect?: Prisma.FileVariantsWhereUniqueInput | Prisma.FileVariantsWhereUniqueInput[]
}

export type FileVariantsUncheckedCreateNestedManyWithoutFileInput = {
  create?: Prisma.XOR<Prisma.FileVariantsCreateWithoutFileInput, Prisma.FileVariantsUncheckedCreateWithoutFileInput> | Prisma.FileVariantsCreateWithoutFileInput[] | Prisma.FileVariantsUncheckedCreateWithoutFileInput[]
  connectOrCreate?: Prisma.FileVariantsCreateOrConnectWithoutFileInput | Prisma.FileVariantsCreateOrConnectWithoutFileInput[]
  createMany?: Prisma.FileVariantsCreateManyFileInputEnvelope
  connect?: Prisma.FileVariantsWhereUniqueInput | Prisma.FileVariantsWhereUniqueInput[]
}

export type FileVariantsUpdateManyWithoutFileNestedInput = {
  create?: Prisma.XOR<Prisma.FileVariantsCreateWithoutFileInput, Prisma.FileVariantsUncheckedCreateWithoutFileInput> | Prisma.FileVariantsCreateWithoutFileInput[] | Prisma.FileVariantsUncheckedCreateWithoutFileInput[]
  connectOrCreate?: Prisma.FileVariantsCreateOrConnectWithoutFileInput | Prisma.FileVariantsCreateOrConnectWithoutFileInput[]
  upsert?: Prisma.FileVariantsUpsertWithWhereUniqueWithoutFileInput | Prisma.FileVariantsUpsertWithWhereUniqueWithoutFileInput[]
  createMany?: Prisma.FileVariantsCreateManyFileInputEnvelope
  set?: Prisma.FileVariantsWhereUniqueInput | Prisma.FileVariantsWhereUniqueInput[]
  disconnect?: Prisma.FileVariantsWhereUniqueInput | Prisma.FileVariantsWhereUniqueInput[]
  delete?: Prisma.FileVariantsWhereUniqueInput | Prisma.FileVariantsWhereUniqueInput[]
  connect?: Prisma.FileVariantsWhereUniqueInput | Prisma.FileVariantsWhereUniqueInput[]
  update?: Prisma.FileVariantsUpdateWithWhereUniqueWithoutFileInput | Prisma.FileVariantsUpdateWithWhereUniqueWithoutFileInput[]
  updateMany?: Prisma.FileVariantsUpdateManyWithWhereWithoutFileInput | Prisma.FileVariantsUpdateManyWithWhereWithoutFileInput[]
  deleteMany?: Prisma.FileVariantsScalarWhereInput | Prisma.FileVariantsScalarWhereInput[]
}

export type FileVariantsUncheckedUpdateManyWithoutFileNestedInput = {
  create?: Prisma.XOR<Prisma.FileVariantsCreateWithoutFileInput, Prisma.FileVariantsUncheckedCreateWithoutFileInput> | Prisma.FileVariantsCreateWithoutFileInput[] | Prisma.FileVariantsUncheckedCreateWithoutFileInput[]
  connectOrCreate?: Prisma.FileVariantsCreateOrConnectWithoutFileInput | Prisma.FileVariantsCreateOrConnectWithoutFileInput[]
  upsert?: Prisma.FileVariantsUpsertWithWhereUniqueWithoutFileInput | Prisma.FileVariantsUpsertWithWhereUniqueWithoutFileInput[]
  createMany?: Prisma.FileVariantsCreateManyFileInputEnvelope
  set?: Prisma.FileVariantsWhereUniqueInput | Prisma.FileVariantsWhereUniqueInput[]
  disconnect?: Prisma.FileVariantsWhereUniqueInput | Prisma.FileVariantsWhereUniqueInput[]
  delete?: Prisma.FileVariantsWhereUniqueInput | Prisma.FileVariantsWhereUniqueInput[]
  connect?: Prisma.FileVariantsWhereUniqueInput | Prisma.FileVariantsWhereUniqueInput[]
  update?: Prisma.FileVariantsUpdateWithWhereUniqueWithoutFileInput | Prisma.FileVariantsUpdateWithWhereUniqueWithoutFileInput[]
  updateMany?: Prisma.FileVariantsUpdateManyWithWhereWithoutFileInput | Prisma.FileVariantsUpdateManyWithWhereWithoutFileInput[]
  deleteMany?: Prisma.FileVariantsScalarWhereInput | Prisma.FileVariantsScalarWhereInput[]
}

export type EnumVariantTypeFieldUpdateOperationsInput = {
  set?: $Enums.VariantType
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type FileVariantsCreateWithoutFileInput = {
  id?: string
  type: $Enums.VariantType
  storageKey: string
  format: string
  width?: number | null
  height?: number | null
  size: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FileVariantsUncheckedCreateWithoutFileInput = {
  id?: string
  type: $Enums.VariantType
  storageKey: string
  format: string
  width?: number | null
  height?: number | null
  size: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FileVariantsCreateOrConnectWithoutFileInput = {
  where: Prisma.FileVariantsWhereUniqueInput
  create: Prisma.XOR<Prisma.FileVariantsCreateWithoutFileInput, Prisma.FileVariantsUncheckedCreateWithoutFileInput>
}

export type FileVariantsCreateManyFileInputEnvelope = {
  data: Prisma.FileVariantsCreateManyFileInput | Prisma.FileVariantsCreateManyFileInput[]
  skipDuplicates?: boolean
}

export type FileVariantsUpsertWithWhereUniqueWithoutFileInput = {
  where: Prisma.FileVariantsWhereUniqueInput
  update: Prisma.XOR<Prisma.FileVariantsUpdateWithoutFileInput, Prisma.FileVariantsUncheckedUpdateWithoutFileInput>
  create: Prisma.XOR<Prisma.FileVariantsCreateWithoutFileInput, Prisma.FileVariantsUncheckedCreateWithoutFileInput>
}

export type FileVariantsUpdateWithWhereUniqueWithoutFileInput = {
  where: Prisma.FileVariantsWhereUniqueInput
  data: Prisma.XOR<Prisma.FileVariantsUpdateWithoutFileInput, Prisma.FileVariantsUncheckedUpdateWithoutFileInput>
}

export type FileVariantsUpdateManyWithWhereWithoutFileInput = {
  where: Prisma.FileVariantsScalarWhereInput
  data: Prisma.XOR<Prisma.FileVariantsUpdateManyMutationInput, Prisma.FileVariantsUncheckedUpdateManyWithoutFileInput>
}

export type FileVariantsScalarWhereInput = {
  AND?: Prisma.FileVariantsScalarWhereInput | Prisma.FileVariantsScalarWhereInput[]
  OR?: Prisma.FileVariantsScalarWhereInput[]
  NOT?: Prisma.FileVariantsScalarWhereInput | Prisma.FileVariantsScalarWhereInput[]
  id?: Prisma.StringFilter<"FileVariants"> | string
  fileId?: Prisma.StringFilter<"FileVariants"> | string
  type?: Prisma.EnumVariantTypeFilter<"FileVariants"> | $Enums.VariantType
  storageKey?: Prisma.StringFilter<"FileVariants"> | string
  format?: Prisma.StringFilter<"FileVariants"> | string
  width?: Prisma.IntNullableFilter<"FileVariants"> | number | null
  height?: Prisma.IntNullableFilter<"FileVariants"> | number | null
  size?: Prisma.IntFilter<"FileVariants"> | number
  createdAt?: Prisma.DateTimeFilter<"FileVariants"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FileVariants"> | Date | string
}

export type FileVariantsCreateManyFileInput = {
  id?: string
  type: $Enums.VariantType
  storageKey: string
  format: string
  width?: number | null
  height?: number | null
  size: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FileVariantsUpdateWithoutFileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumVariantTypeFieldUpdateOperationsInput | $Enums.VariantType
  storageKey?: Prisma.StringFieldUpdateOperationsInput | string
  format?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  size?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FileVariantsUncheckedUpdateWithoutFileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumVariantTypeFieldUpdateOperationsInput | $Enums.VariantType
  storageKey?: Prisma.StringFieldUpdateOperationsInput | string
  format?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  size?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FileVariantsUncheckedUpdateManyWithoutFileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumVariantTypeFieldUpdateOperationsInput | $Enums.VariantType
  storageKey?: Prisma.StringFieldUpdateOperationsInput | string
  format?: Prisma.StringFieldUpdateOperationsInput | string
  width?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  height?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  size?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type FileVariantsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fileId?: boolean
  type?: boolean
  storageKey?: boolean
  format?: boolean
  width?: boolean
  height?: boolean
  size?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  file?: boolean | Prisma.FilesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fileVariants"]>

export type FileVariantsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fileId?: boolean
  type?: boolean
  storageKey?: boolean
  format?: boolean
  width?: boolean
  height?: boolean
  size?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  file?: boolean | Prisma.FilesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fileVariants"]>

export type FileVariantsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fileId?: boolean
  type?: boolean
  storageKey?: boolean
  format?: boolean
  width?: boolean
  height?: boolean
  size?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  file?: boolean | Prisma.FilesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["fileVariants"]>

export type FileVariantsSelectScalar = {
  id?: boolean
  fileId?: boolean
  type?: boolean
  storageKey?: boolean
  format?: boolean
  width?: boolean
  height?: boolean
  size?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type FileVariantsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "fileId" | "type" | "storageKey" | "format" | "width" | "height" | "size" | "createdAt" | "updatedAt", ExtArgs["result"]["fileVariants"]>
export type FileVariantsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  file?: boolean | Prisma.FilesDefaultArgs<ExtArgs>
}
export type FileVariantsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  file?: boolean | Prisma.FilesDefaultArgs<ExtArgs>
}
export type FileVariantsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  file?: boolean | Prisma.FilesDefaultArgs<ExtArgs>
}

export type $FileVariantsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FileVariants"
  objects: {
    file: Prisma.$FilesPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    fileId: string
    type: $Enums.VariantType
    storageKey: string
    format: string
    width: number | null
    height: number | null
    size: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["fileVariants"]>
  composites: {}
}

export type FileVariantsGetPayload<S extends boolean | null | undefined | FileVariantsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FileVariantsPayload, S>

export type FileVariantsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FileVariantsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FileVariantsCountAggregateInputType | true
  }

export interface FileVariantsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FileVariants'], meta: { name: 'FileVariants' } }
  /**
   * Find zero or one FileVariants that matches the filter.
   * @param {FileVariantsFindUniqueArgs} args - Arguments to find a FileVariants
   * @example
   * // Get one FileVariants
   * const fileVariants = await prisma.fileVariants.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FileVariantsFindUniqueArgs>(args: Prisma.SelectSubset<T, FileVariantsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FileVariantsClient<runtime.Types.Result.GetResult<Prisma.$FileVariantsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FileVariants that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FileVariantsFindUniqueOrThrowArgs} args - Arguments to find a FileVariants
   * @example
   * // Get one FileVariants
   * const fileVariants = await prisma.fileVariants.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FileVariantsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FileVariantsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FileVariantsClient<runtime.Types.Result.GetResult<Prisma.$FileVariantsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FileVariants that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileVariantsFindFirstArgs} args - Arguments to find a FileVariants
   * @example
   * // Get one FileVariants
   * const fileVariants = await prisma.fileVariants.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FileVariantsFindFirstArgs>(args?: Prisma.SelectSubset<T, FileVariantsFindFirstArgs<ExtArgs>>): Prisma.Prisma__FileVariantsClient<runtime.Types.Result.GetResult<Prisma.$FileVariantsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FileVariants that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileVariantsFindFirstOrThrowArgs} args - Arguments to find a FileVariants
   * @example
   * // Get one FileVariants
   * const fileVariants = await prisma.fileVariants.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FileVariantsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FileVariantsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FileVariantsClient<runtime.Types.Result.GetResult<Prisma.$FileVariantsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FileVariants that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileVariantsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FileVariants
   * const fileVariants = await prisma.fileVariants.findMany()
   * 
   * // Get first 10 FileVariants
   * const fileVariants = await prisma.fileVariants.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const fileVariantsWithIdOnly = await prisma.fileVariants.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FileVariantsFindManyArgs>(args?: Prisma.SelectSubset<T, FileVariantsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FileVariantsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FileVariants.
   * @param {FileVariantsCreateArgs} args - Arguments to create a FileVariants.
   * @example
   * // Create one FileVariants
   * const FileVariants = await prisma.fileVariants.create({
   *   data: {
   *     // ... data to create a FileVariants
   *   }
   * })
   * 
   */
  create<T extends FileVariantsCreateArgs>(args: Prisma.SelectSubset<T, FileVariantsCreateArgs<ExtArgs>>): Prisma.Prisma__FileVariantsClient<runtime.Types.Result.GetResult<Prisma.$FileVariantsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FileVariants.
   * @param {FileVariantsCreateManyArgs} args - Arguments to create many FileVariants.
   * @example
   * // Create many FileVariants
   * const fileVariants = await prisma.fileVariants.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FileVariantsCreateManyArgs>(args?: Prisma.SelectSubset<T, FileVariantsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FileVariants and returns the data saved in the database.
   * @param {FileVariantsCreateManyAndReturnArgs} args - Arguments to create many FileVariants.
   * @example
   * // Create many FileVariants
   * const fileVariants = await prisma.fileVariants.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FileVariants and only return the `id`
   * const fileVariantsWithIdOnly = await prisma.fileVariants.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FileVariantsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FileVariantsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FileVariantsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FileVariants.
   * @param {FileVariantsDeleteArgs} args - Arguments to delete one FileVariants.
   * @example
   * // Delete one FileVariants
   * const FileVariants = await prisma.fileVariants.delete({
   *   where: {
   *     // ... filter to delete one FileVariants
   *   }
   * })
   * 
   */
  delete<T extends FileVariantsDeleteArgs>(args: Prisma.SelectSubset<T, FileVariantsDeleteArgs<ExtArgs>>): Prisma.Prisma__FileVariantsClient<runtime.Types.Result.GetResult<Prisma.$FileVariantsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FileVariants.
   * @param {FileVariantsUpdateArgs} args - Arguments to update one FileVariants.
   * @example
   * // Update one FileVariants
   * const fileVariants = await prisma.fileVariants.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FileVariantsUpdateArgs>(args: Prisma.SelectSubset<T, FileVariantsUpdateArgs<ExtArgs>>): Prisma.Prisma__FileVariantsClient<runtime.Types.Result.GetResult<Prisma.$FileVariantsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FileVariants.
   * @param {FileVariantsDeleteManyArgs} args - Arguments to filter FileVariants to delete.
   * @example
   * // Delete a few FileVariants
   * const { count } = await prisma.fileVariants.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FileVariantsDeleteManyArgs>(args?: Prisma.SelectSubset<T, FileVariantsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FileVariants.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileVariantsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FileVariants
   * const fileVariants = await prisma.fileVariants.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FileVariantsUpdateManyArgs>(args: Prisma.SelectSubset<T, FileVariantsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FileVariants and returns the data updated in the database.
   * @param {FileVariantsUpdateManyAndReturnArgs} args - Arguments to update many FileVariants.
   * @example
   * // Update many FileVariants
   * const fileVariants = await prisma.fileVariants.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FileVariants and only return the `id`
   * const fileVariantsWithIdOnly = await prisma.fileVariants.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FileVariantsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FileVariantsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FileVariantsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FileVariants.
   * @param {FileVariantsUpsertArgs} args - Arguments to update or create a FileVariants.
   * @example
   * // Update or create a FileVariants
   * const fileVariants = await prisma.fileVariants.upsert({
   *   create: {
   *     // ... data to create a FileVariants
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FileVariants we want to update
   *   }
   * })
   */
  upsert<T extends FileVariantsUpsertArgs>(args: Prisma.SelectSubset<T, FileVariantsUpsertArgs<ExtArgs>>): Prisma.Prisma__FileVariantsClient<runtime.Types.Result.GetResult<Prisma.$FileVariantsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FileVariants.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileVariantsCountArgs} args - Arguments to filter FileVariants to count.
   * @example
   * // Count the number of FileVariants
   * const count = await prisma.fileVariants.count({
   *   where: {
   *     // ... the filter for the FileVariants we want to count
   *   }
   * })
  **/
  count<T extends FileVariantsCountArgs>(
    args?: Prisma.Subset<T, FileVariantsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FileVariantsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FileVariants.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileVariantsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FileVariantsAggregateArgs>(args: Prisma.Subset<T, FileVariantsAggregateArgs>): Prisma.PrismaPromise<GetFileVariantsAggregateType<T>>

  /**
   * Group by FileVariants.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FileVariantsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FileVariantsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FileVariantsGroupByArgs['orderBy'] }
      : { orderBy?: FileVariantsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FileVariantsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFileVariantsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FileVariants model
 */
readonly fields: FileVariantsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FileVariants.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FileVariantsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  file<T extends Prisma.FilesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FilesDefaultArgs<ExtArgs>>): Prisma.Prisma__FilesClient<runtime.Types.Result.GetResult<Prisma.$FilesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FileVariants model
 */
export interface FileVariantsFieldRefs {
  readonly id: Prisma.FieldRef<"FileVariants", 'String'>
  readonly fileId: Prisma.FieldRef<"FileVariants", 'String'>
  readonly type: Prisma.FieldRef<"FileVariants", 'VariantType'>
  readonly storageKey: Prisma.FieldRef<"FileVariants", 'String'>
  readonly format: Prisma.FieldRef<"FileVariants", 'String'>
  readonly width: Prisma.FieldRef<"FileVariants", 'Int'>
  readonly height: Prisma.FieldRef<"FileVariants", 'Int'>
  readonly size: Prisma.FieldRef<"FileVariants", 'Int'>
  readonly createdAt: Prisma.FieldRef<"FileVariants", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"FileVariants", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FileVariants findUnique
 */
export type FileVariantsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileVariants
   */
  select?: Prisma.FileVariantsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileVariants
   */
  omit?: Prisma.FileVariantsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileVariantsInclude<ExtArgs> | null
  /**
   * Filter, which FileVariants to fetch.
   */
  where: Prisma.FileVariantsWhereUniqueInput
}

/**
 * FileVariants findUniqueOrThrow
 */
export type FileVariantsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileVariants
   */
  select?: Prisma.FileVariantsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileVariants
   */
  omit?: Prisma.FileVariantsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileVariantsInclude<ExtArgs> | null
  /**
   * Filter, which FileVariants to fetch.
   */
  where: Prisma.FileVariantsWhereUniqueInput
}

/**
 * FileVariants findFirst
 */
export type FileVariantsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileVariants
   */
  select?: Prisma.FileVariantsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileVariants
   */
  omit?: Prisma.FileVariantsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileVariantsInclude<ExtArgs> | null
  /**
   * Filter, which FileVariants to fetch.
   */
  where?: Prisma.FileVariantsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FileVariants to fetch.
   */
  orderBy?: Prisma.FileVariantsOrderByWithRelationInput | Prisma.FileVariantsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FileVariants.
   */
  cursor?: Prisma.FileVariantsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FileVariants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FileVariants.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FileVariants.
   */
  distinct?: Prisma.FileVariantsScalarFieldEnum | Prisma.FileVariantsScalarFieldEnum[]
}

/**
 * FileVariants findFirstOrThrow
 */
export type FileVariantsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileVariants
   */
  select?: Prisma.FileVariantsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileVariants
   */
  omit?: Prisma.FileVariantsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileVariantsInclude<ExtArgs> | null
  /**
   * Filter, which FileVariants to fetch.
   */
  where?: Prisma.FileVariantsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FileVariants to fetch.
   */
  orderBy?: Prisma.FileVariantsOrderByWithRelationInput | Prisma.FileVariantsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FileVariants.
   */
  cursor?: Prisma.FileVariantsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FileVariants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FileVariants.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FileVariants.
   */
  distinct?: Prisma.FileVariantsScalarFieldEnum | Prisma.FileVariantsScalarFieldEnum[]
}

/**
 * FileVariants findMany
 */
export type FileVariantsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileVariants
   */
  select?: Prisma.FileVariantsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileVariants
   */
  omit?: Prisma.FileVariantsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileVariantsInclude<ExtArgs> | null
  /**
   * Filter, which FileVariants to fetch.
   */
  where?: Prisma.FileVariantsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FileVariants to fetch.
   */
  orderBy?: Prisma.FileVariantsOrderByWithRelationInput | Prisma.FileVariantsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FileVariants.
   */
  cursor?: Prisma.FileVariantsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FileVariants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FileVariants.
   */
  skip?: number
  distinct?: Prisma.FileVariantsScalarFieldEnum | Prisma.FileVariantsScalarFieldEnum[]
}

/**
 * FileVariants create
 */
export type FileVariantsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileVariants
   */
  select?: Prisma.FileVariantsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileVariants
   */
  omit?: Prisma.FileVariantsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileVariantsInclude<ExtArgs> | null
  /**
   * The data needed to create a FileVariants.
   */
  data: Prisma.XOR<Prisma.FileVariantsCreateInput, Prisma.FileVariantsUncheckedCreateInput>
}

/**
 * FileVariants createMany
 */
export type FileVariantsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FileVariants.
   */
  data: Prisma.FileVariantsCreateManyInput | Prisma.FileVariantsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FileVariants createManyAndReturn
 */
export type FileVariantsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileVariants
   */
  select?: Prisma.FileVariantsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FileVariants
   */
  omit?: Prisma.FileVariantsOmit<ExtArgs> | null
  /**
   * The data used to create many FileVariants.
   */
  data: Prisma.FileVariantsCreateManyInput | Prisma.FileVariantsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileVariantsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * FileVariants update
 */
export type FileVariantsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileVariants
   */
  select?: Prisma.FileVariantsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileVariants
   */
  omit?: Prisma.FileVariantsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileVariantsInclude<ExtArgs> | null
  /**
   * The data needed to update a FileVariants.
   */
  data: Prisma.XOR<Prisma.FileVariantsUpdateInput, Prisma.FileVariantsUncheckedUpdateInput>
  /**
   * Choose, which FileVariants to update.
   */
  where: Prisma.FileVariantsWhereUniqueInput
}

/**
 * FileVariants updateMany
 */
export type FileVariantsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FileVariants.
   */
  data: Prisma.XOR<Prisma.FileVariantsUpdateManyMutationInput, Prisma.FileVariantsUncheckedUpdateManyInput>
  /**
   * Filter which FileVariants to update
   */
  where?: Prisma.FileVariantsWhereInput
  /**
   * Limit how many FileVariants to update.
   */
  limit?: number
}

/**
 * FileVariants updateManyAndReturn
 */
export type FileVariantsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileVariants
   */
  select?: Prisma.FileVariantsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FileVariants
   */
  omit?: Prisma.FileVariantsOmit<ExtArgs> | null
  /**
   * The data used to update FileVariants.
   */
  data: Prisma.XOR<Prisma.FileVariantsUpdateManyMutationInput, Prisma.FileVariantsUncheckedUpdateManyInput>
  /**
   * Filter which FileVariants to update
   */
  where?: Prisma.FileVariantsWhereInput
  /**
   * Limit how many FileVariants to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileVariantsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * FileVariants upsert
 */
export type FileVariantsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileVariants
   */
  select?: Prisma.FileVariantsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileVariants
   */
  omit?: Prisma.FileVariantsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileVariantsInclude<ExtArgs> | null
  /**
   * The filter to search for the FileVariants to update in case it exists.
   */
  where: Prisma.FileVariantsWhereUniqueInput
  /**
   * In case the FileVariants found by the `where` argument doesn't exist, create a new FileVariants with this data.
   */
  create: Prisma.XOR<Prisma.FileVariantsCreateInput, Prisma.FileVariantsUncheckedCreateInput>
  /**
   * In case the FileVariants was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FileVariantsUpdateInput, Prisma.FileVariantsUncheckedUpdateInput>
}

/**
 * FileVariants delete
 */
export type FileVariantsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileVariants
   */
  select?: Prisma.FileVariantsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileVariants
   */
  omit?: Prisma.FileVariantsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileVariantsInclude<ExtArgs> | null
  /**
   * Filter which FileVariants to delete.
   */
  where: Prisma.FileVariantsWhereUniqueInput
}

/**
 * FileVariants deleteMany
 */
export type FileVariantsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FileVariants to delete
   */
  where?: Prisma.FileVariantsWhereInput
  /**
   * Limit how many FileVariants to delete.
   */
  limit?: number
}

/**
 * FileVariants without action
 */
export type FileVariantsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FileVariants
   */
  select?: Prisma.FileVariantsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FileVariants
   */
  omit?: Prisma.FileVariantsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileVariantsInclude<ExtArgs> | null
}
