
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Folders` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Folders
 * 
 */
export type FoldersModel = runtime.Types.Result.DefaultSelection<Prisma.$FoldersPayload>

export type AggregateFolders = {
  _count: FoldersCountAggregateOutputType | null
  _min: FoldersMinAggregateOutputType | null
  _max: FoldersMaxAggregateOutputType | null
}

export type FoldersMinAggregateOutputType = {
  id: string | null
  name: string | null
  parentId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FoldersMaxAggregateOutputType = {
  id: string | null
  name: string | null
  parentId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FoldersCountAggregateOutputType = {
  id: number
  name: number
  parentId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type FoldersMinAggregateInputType = {
  id?: true
  name?: true
  parentId?: true
  createdAt?: true
  updatedAt?: true
}

export type FoldersMaxAggregateInputType = {
  id?: true
  name?: true
  parentId?: true
  createdAt?: true
  updatedAt?: true
}

export type FoldersCountAggregateInputType = {
  id?: true
  name?: true
  parentId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type FoldersAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Folders to aggregate.
   */
  where?: Prisma.FoldersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Folders to fetch.
   */
  orderBy?: Prisma.FoldersOrderByWithRelationInput | Prisma.FoldersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FoldersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Folders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Folders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Folders
  **/
  _count?: true | FoldersCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FoldersMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FoldersMaxAggregateInputType
}

export type GetFoldersAggregateType<T extends FoldersAggregateArgs> = {
      [P in keyof T & keyof AggregateFolders]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFolders[P]>
    : Prisma.GetScalarType<T[P], AggregateFolders[P]>
}




export type FoldersGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FoldersWhereInput
  orderBy?: Prisma.FoldersOrderByWithAggregationInput | Prisma.FoldersOrderByWithAggregationInput[]
  by: Prisma.FoldersScalarFieldEnum[] | Prisma.FoldersScalarFieldEnum
  having?: Prisma.FoldersScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FoldersCountAggregateInputType | true
  _min?: FoldersMinAggregateInputType
  _max?: FoldersMaxAggregateInputType
}

export type FoldersGroupByOutputType = {
  id: string
  name: string
  parentId: string | null
  createdAt: Date
  updatedAt: Date
  _count: FoldersCountAggregateOutputType | null
  _min: FoldersMinAggregateOutputType | null
  _max: FoldersMaxAggregateOutputType | null
}

type GetFoldersGroupByPayload<T extends FoldersGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FoldersGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FoldersGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FoldersGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FoldersGroupByOutputType[P]>
      }
    >
  >



export type FoldersWhereInput = {
  AND?: Prisma.FoldersWhereInput | Prisma.FoldersWhereInput[]
  OR?: Prisma.FoldersWhereInput[]
  NOT?: Prisma.FoldersWhereInput | Prisma.FoldersWhereInput[]
  id?: Prisma.StringFilter<"Folders"> | string
  name?: Prisma.StringFilter<"Folders"> | string
  parentId?: Prisma.StringNullableFilter<"Folders"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Folders"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Folders"> | Date | string
  parent?: Prisma.XOR<Prisma.FoldersNullableScalarRelationFilter, Prisma.FoldersWhereInput> | null
  children?: Prisma.FoldersListRelationFilter
  files?: Prisma.FilesListRelationFilter
}

export type FoldersOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  parentId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  parent?: Prisma.FoldersOrderByWithRelationInput
  children?: Prisma.FoldersOrderByRelationAggregateInput
  files?: Prisma.FilesOrderByRelationAggregateInput
}

export type FoldersWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.FoldersWhereInput | Prisma.FoldersWhereInput[]
  OR?: Prisma.FoldersWhereInput[]
  NOT?: Prisma.FoldersWhereInput | Prisma.FoldersWhereInput[]
  name?: Prisma.StringFilter<"Folders"> | string
  parentId?: Prisma.StringNullableFilter<"Folders"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Folders"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Folders"> | Date | string
  parent?: Prisma.XOR<Prisma.FoldersNullableScalarRelationFilter, Prisma.FoldersWhereInput> | null
  children?: Prisma.FoldersListRelationFilter
  files?: Prisma.FilesListRelationFilter
}, "id">

export type FoldersOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  parentId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.FoldersCountOrderByAggregateInput
  _max?: Prisma.FoldersMaxOrderByAggregateInput
  _min?: Prisma.FoldersMinOrderByAggregateInput
}

export type FoldersScalarWhereWithAggregatesInput = {
  AND?: Prisma.FoldersScalarWhereWithAggregatesInput | Prisma.FoldersScalarWhereWithAggregatesInput[]
  OR?: Prisma.FoldersScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FoldersScalarWhereWithAggregatesInput | Prisma.FoldersScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Folders"> | string
  name?: Prisma.StringWithAggregatesFilter<"Folders"> | string
  parentId?: Prisma.StringNullableWithAggregatesFilter<"Folders"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Folders"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Folders"> | Date | string
}

export type FoldersCreateInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  parent?: Prisma.FoldersCreateNestedOneWithoutChildrenInput
  children?: Prisma.FoldersCreateNestedManyWithoutParentInput
  files?: Prisma.FilesCreateNestedManyWithoutFolderInput
}

export type FoldersUncheckedCreateInput = {
  id?: string
  name: string
  parentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  children?: Prisma.FoldersUncheckedCreateNestedManyWithoutParentInput
  files?: Prisma.FilesUncheckedCreateNestedManyWithoutFolderInput
}

export type FoldersUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  parent?: Prisma.FoldersUpdateOneWithoutChildrenNestedInput
  children?: Prisma.FoldersUpdateManyWithoutParentNestedInput
  files?: Prisma.FilesUpdateManyWithoutFolderNestedInput
}

export type FoldersUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  children?: Prisma.FoldersUncheckedUpdateManyWithoutParentNestedInput
  files?: Prisma.FilesUncheckedUpdateManyWithoutFolderNestedInput
}

export type FoldersCreateManyInput = {
  id?: string
  name: string
  parentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FoldersUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FoldersUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FoldersNullableScalarRelationFilter = {
  is?: Prisma.FoldersWhereInput | null
  isNot?: Prisma.FoldersWhereInput | null
}

export type FoldersListRelationFilter = {
  every?: Prisma.FoldersWhereInput
  some?: Prisma.FoldersWhereInput
  none?: Prisma.FoldersWhereInput
}

export type FoldersOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FoldersCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  parentId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FoldersMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  parentId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FoldersMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  parentId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FoldersCreateNestedOneWithoutChildrenInput = {
  create?: Prisma.XOR<Prisma.FoldersCreateWithoutChildrenInput, Prisma.FoldersUncheckedCreateWithoutChildrenInput>
  connectOrCreate?: Prisma.FoldersCreateOrConnectWithoutChildrenInput
  connect?: Prisma.FoldersWhereUniqueInput
}

export type FoldersCreateNestedManyWithoutParentInput = {
  create?: Prisma.XOR<Prisma.FoldersCreateWithoutParentInput, Prisma.FoldersUncheckedCreateWithoutParentInput> | Prisma.FoldersCreateWithoutParentInput[] | Prisma.FoldersUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.FoldersCreateOrConnectWithoutParentInput | Prisma.FoldersCreateOrConnectWithoutParentInput[]
  createMany?: Prisma.FoldersCreateManyParentInputEnvelope
  connect?: Prisma.FoldersWhereUniqueInput | Prisma.FoldersWhereUniqueInput[]
}

export type FoldersUncheckedCreateNestedManyWithoutParentInput = {
  create?: Prisma.XOR<Prisma.FoldersCreateWithoutParentInput, Prisma.FoldersUncheckedCreateWithoutParentInput> | Prisma.FoldersCreateWithoutParentInput[] | Prisma.FoldersUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.FoldersCreateOrConnectWithoutParentInput | Prisma.FoldersCreateOrConnectWithoutParentInput[]
  createMany?: Prisma.FoldersCreateManyParentInputEnvelope
  connect?: Prisma.FoldersWhereUniqueInput | Prisma.FoldersWhereUniqueInput[]
}

export type FoldersUpdateOneWithoutChildrenNestedInput = {
  create?: Prisma.XOR<Prisma.FoldersCreateWithoutChildrenInput, Prisma.FoldersUncheckedCreateWithoutChildrenInput>
  connectOrCreate?: Prisma.FoldersCreateOrConnectWithoutChildrenInput
  upsert?: Prisma.FoldersUpsertWithoutChildrenInput
  disconnect?: Prisma.FoldersWhereInput | boolean
  delete?: Prisma.FoldersWhereInput | boolean
  connect?: Prisma.FoldersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FoldersUpdateToOneWithWhereWithoutChildrenInput, Prisma.FoldersUpdateWithoutChildrenInput>, Prisma.FoldersUncheckedUpdateWithoutChildrenInput>
}

export type FoldersUpdateManyWithoutParentNestedInput = {
  create?: Prisma.XOR<Prisma.FoldersCreateWithoutParentInput, Prisma.FoldersUncheckedCreateWithoutParentInput> | Prisma.FoldersCreateWithoutParentInput[] | Prisma.FoldersUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.FoldersCreateOrConnectWithoutParentInput | Prisma.FoldersCreateOrConnectWithoutParentInput[]
  upsert?: Prisma.FoldersUpsertWithWhereUniqueWithoutParentInput | Prisma.FoldersUpsertWithWhereUniqueWithoutParentInput[]
  createMany?: Prisma.FoldersCreateManyParentInputEnvelope
  set?: Prisma.FoldersWhereUniqueInput | Prisma.FoldersWhereUniqueInput[]
  disconnect?: Prisma.FoldersWhereUniqueInput | Prisma.FoldersWhereUniqueInput[]
  delete?: Prisma.FoldersWhereUniqueInput | Prisma.FoldersWhereUniqueInput[]
  connect?: Prisma.FoldersWhereUniqueInput | Prisma.FoldersWhereUniqueInput[]
  update?: Prisma.FoldersUpdateWithWhereUniqueWithoutParentInput | Prisma.FoldersUpdateWithWhereUniqueWithoutParentInput[]
  updateMany?: Prisma.FoldersUpdateManyWithWhereWithoutParentInput | Prisma.FoldersUpdateManyWithWhereWithoutParentInput[]
  deleteMany?: Prisma.FoldersScalarWhereInput | Prisma.FoldersScalarWhereInput[]
}

export type FoldersUncheckedUpdateManyWithoutParentNestedInput = {
  create?: Prisma.XOR<Prisma.FoldersCreateWithoutParentInput, Prisma.FoldersUncheckedCreateWithoutParentInput> | Prisma.FoldersCreateWithoutParentInput[] | Prisma.FoldersUncheckedCreateWithoutParentInput[]
  connectOrCreate?: Prisma.FoldersCreateOrConnectWithoutParentInput | Prisma.FoldersCreateOrConnectWithoutParentInput[]
  upsert?: Prisma.FoldersUpsertWithWhereUniqueWithoutParentInput | Prisma.FoldersUpsertWithWhereUniqueWithoutParentInput[]
  createMany?: Prisma.FoldersCreateManyParentInputEnvelope
  set?: Prisma.FoldersWhereUniqueInput | Prisma.FoldersWhereUniqueInput[]
  disconnect?: Prisma.FoldersWhereUniqueInput | Prisma.FoldersWhereUniqueInput[]
  delete?: Prisma.FoldersWhereUniqueInput | Prisma.FoldersWhereUniqueInput[]
  connect?: Prisma.FoldersWhereUniqueInput | Prisma.FoldersWhereUniqueInput[]
  update?: Prisma.FoldersUpdateWithWhereUniqueWithoutParentInput | Prisma.FoldersUpdateWithWhereUniqueWithoutParentInput[]
  updateMany?: Prisma.FoldersUpdateManyWithWhereWithoutParentInput | Prisma.FoldersUpdateManyWithWhereWithoutParentInput[]
  deleteMany?: Prisma.FoldersScalarWhereInput | Prisma.FoldersScalarWhereInput[]
}

export type FoldersCreateNestedOneWithoutFilesInput = {
  create?: Prisma.XOR<Prisma.FoldersCreateWithoutFilesInput, Prisma.FoldersUncheckedCreateWithoutFilesInput>
  connectOrCreate?: Prisma.FoldersCreateOrConnectWithoutFilesInput
  connect?: Prisma.FoldersWhereUniqueInput
}

export type FoldersUpdateOneWithoutFilesNestedInput = {
  create?: Prisma.XOR<Prisma.FoldersCreateWithoutFilesInput, Prisma.FoldersUncheckedCreateWithoutFilesInput>
  connectOrCreate?: Prisma.FoldersCreateOrConnectWithoutFilesInput
  upsert?: Prisma.FoldersUpsertWithoutFilesInput
  disconnect?: Prisma.FoldersWhereInput | boolean
  delete?: Prisma.FoldersWhereInput | boolean
  connect?: Prisma.FoldersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FoldersUpdateToOneWithWhereWithoutFilesInput, Prisma.FoldersUpdateWithoutFilesInput>, Prisma.FoldersUncheckedUpdateWithoutFilesInput>
}

export type FoldersCreateWithoutChildrenInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  parent?: Prisma.FoldersCreateNestedOneWithoutChildrenInput
  files?: Prisma.FilesCreateNestedManyWithoutFolderInput
}

export type FoldersUncheckedCreateWithoutChildrenInput = {
  id?: string
  name: string
  parentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  files?: Prisma.FilesUncheckedCreateNestedManyWithoutFolderInput
}

export type FoldersCreateOrConnectWithoutChildrenInput = {
  where: Prisma.FoldersWhereUniqueInput
  create: Prisma.XOR<Prisma.FoldersCreateWithoutChildrenInput, Prisma.FoldersUncheckedCreateWithoutChildrenInput>
}

export type FoldersCreateWithoutParentInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  children?: Prisma.FoldersCreateNestedManyWithoutParentInput
  files?: Prisma.FilesCreateNestedManyWithoutFolderInput
}

export type FoldersUncheckedCreateWithoutParentInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  children?: Prisma.FoldersUncheckedCreateNestedManyWithoutParentInput
  files?: Prisma.FilesUncheckedCreateNestedManyWithoutFolderInput
}

export type FoldersCreateOrConnectWithoutParentInput = {
  where: Prisma.FoldersWhereUniqueInput
  create: Prisma.XOR<Prisma.FoldersCreateWithoutParentInput, Prisma.FoldersUncheckedCreateWithoutParentInput>
}

export type FoldersCreateManyParentInputEnvelope = {
  data: Prisma.FoldersCreateManyParentInput | Prisma.FoldersCreateManyParentInput[]
  skipDuplicates?: boolean
}

export type FoldersUpsertWithoutChildrenInput = {
  update: Prisma.XOR<Prisma.FoldersUpdateWithoutChildrenInput, Prisma.FoldersUncheckedUpdateWithoutChildrenInput>
  create: Prisma.XOR<Prisma.FoldersCreateWithoutChildrenInput, Prisma.FoldersUncheckedCreateWithoutChildrenInput>
  where?: Prisma.FoldersWhereInput
}

export type FoldersUpdateToOneWithWhereWithoutChildrenInput = {
  where?: Prisma.FoldersWhereInput
  data: Prisma.XOR<Prisma.FoldersUpdateWithoutChildrenInput, Prisma.FoldersUncheckedUpdateWithoutChildrenInput>
}

export type FoldersUpdateWithoutChildrenInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  parent?: Prisma.FoldersUpdateOneWithoutChildrenNestedInput
  files?: Prisma.FilesUpdateManyWithoutFolderNestedInput
}

export type FoldersUncheckedUpdateWithoutChildrenInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  files?: Prisma.FilesUncheckedUpdateManyWithoutFolderNestedInput
}

export type FoldersUpsertWithWhereUniqueWithoutParentInput = {
  where: Prisma.FoldersWhereUniqueInput
  update: Prisma.XOR<Prisma.FoldersUpdateWithoutParentInput, Prisma.FoldersUncheckedUpdateWithoutParentInput>
  create: Prisma.XOR<Prisma.FoldersCreateWithoutParentInput, Prisma.FoldersUncheckedCreateWithoutParentInput>
}

export type FoldersUpdateWithWhereUniqueWithoutParentInput = {
  where: Prisma.FoldersWhereUniqueInput
  data: Prisma.XOR<Prisma.FoldersUpdateWithoutParentInput, Prisma.FoldersUncheckedUpdateWithoutParentInput>
}

export type FoldersUpdateManyWithWhereWithoutParentInput = {
  where: Prisma.FoldersScalarWhereInput
  data: Prisma.XOR<Prisma.FoldersUpdateManyMutationInput, Prisma.FoldersUncheckedUpdateManyWithoutParentInput>
}

export type FoldersScalarWhereInput = {
  AND?: Prisma.FoldersScalarWhereInput | Prisma.FoldersScalarWhereInput[]
  OR?: Prisma.FoldersScalarWhereInput[]
  NOT?: Prisma.FoldersScalarWhereInput | Prisma.FoldersScalarWhereInput[]
  id?: Prisma.StringFilter<"Folders"> | string
  name?: Prisma.StringFilter<"Folders"> | string
  parentId?: Prisma.StringNullableFilter<"Folders"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Folders"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Folders"> | Date | string
}

export type FoldersCreateWithoutFilesInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  parent?: Prisma.FoldersCreateNestedOneWithoutChildrenInput
  children?: Prisma.FoldersCreateNestedManyWithoutParentInput
}

export type FoldersUncheckedCreateWithoutFilesInput = {
  id?: string
  name: string
  parentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  children?: Prisma.FoldersUncheckedCreateNestedManyWithoutParentInput
}

export type FoldersCreateOrConnectWithoutFilesInput = {
  where: Prisma.FoldersWhereUniqueInput
  create: Prisma.XOR<Prisma.FoldersCreateWithoutFilesInput, Prisma.FoldersUncheckedCreateWithoutFilesInput>
}

export type FoldersUpsertWithoutFilesInput = {
  update: Prisma.XOR<Prisma.FoldersUpdateWithoutFilesInput, Prisma.FoldersUncheckedUpdateWithoutFilesInput>
  create: Prisma.XOR<Prisma.FoldersCreateWithoutFilesInput, Prisma.FoldersUncheckedCreateWithoutFilesInput>
  where?: Prisma.FoldersWhereInput
}

export type FoldersUpdateToOneWithWhereWithoutFilesInput = {
  where?: Prisma.FoldersWhereInput
  data: Prisma.XOR<Prisma.FoldersUpdateWithoutFilesInput, Prisma.FoldersUncheckedUpdateWithoutFilesInput>
}

export type FoldersUpdateWithoutFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  parent?: Prisma.FoldersUpdateOneWithoutChildrenNestedInput
  children?: Prisma.FoldersUpdateManyWithoutParentNestedInput
}

export type FoldersUncheckedUpdateWithoutFilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  parentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  children?: Prisma.FoldersUncheckedUpdateManyWithoutParentNestedInput
}

export type FoldersCreateManyParentInput = {
  id?: string
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FoldersUpdateWithoutParentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  children?: Prisma.FoldersUpdateManyWithoutParentNestedInput
  files?: Prisma.FilesUpdateManyWithoutFolderNestedInput
}

export type FoldersUncheckedUpdateWithoutParentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  children?: Prisma.FoldersUncheckedUpdateManyWithoutParentNestedInput
  files?: Prisma.FilesUncheckedUpdateManyWithoutFolderNestedInput
}

export type FoldersUncheckedUpdateManyWithoutParentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type FoldersCountOutputType
 */

export type FoldersCountOutputType = {
  children: number
  files: number
}

export type FoldersCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  children?: boolean | FoldersCountOutputTypeCountChildrenArgs
  files?: boolean | FoldersCountOutputTypeCountFilesArgs
}

/**
 * FoldersCountOutputType without action
 */
export type FoldersCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FoldersCountOutputType
   */
  select?: Prisma.FoldersCountOutputTypeSelect<ExtArgs> | null
}

/**
 * FoldersCountOutputType without action
 */
export type FoldersCountOutputTypeCountChildrenArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FoldersWhereInput
}

/**
 * FoldersCountOutputType without action
 */
export type FoldersCountOutputTypeCountFilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FilesWhereInput
}


export type FoldersSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  parentId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  parent?: boolean | Prisma.Folders$parentArgs<ExtArgs>
  children?: boolean | Prisma.Folders$childrenArgs<ExtArgs>
  files?: boolean | Prisma.Folders$filesArgs<ExtArgs>
  _count?: boolean | Prisma.FoldersCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["folders"]>

export type FoldersSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  parentId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  parent?: boolean | Prisma.Folders$parentArgs<ExtArgs>
}, ExtArgs["result"]["folders"]>

export type FoldersSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  parentId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  parent?: boolean | Prisma.Folders$parentArgs<ExtArgs>
}, ExtArgs["result"]["folders"]>

export type FoldersSelectScalar = {
  id?: boolean
  name?: boolean
  parentId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type FoldersOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "parentId" | "createdAt" | "updatedAt", ExtArgs["result"]["folders"]>
export type FoldersInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  parent?: boolean | Prisma.Folders$parentArgs<ExtArgs>
  children?: boolean | Prisma.Folders$childrenArgs<ExtArgs>
  files?: boolean | Prisma.Folders$filesArgs<ExtArgs>
  _count?: boolean | Prisma.FoldersCountOutputTypeDefaultArgs<ExtArgs>
}
export type FoldersIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  parent?: boolean | Prisma.Folders$parentArgs<ExtArgs>
}
export type FoldersIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  parent?: boolean | Prisma.Folders$parentArgs<ExtArgs>
}

export type $FoldersPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Folders"
  objects: {
    parent: Prisma.$FoldersPayload<ExtArgs> | null
    children: Prisma.$FoldersPayload<ExtArgs>[]
    files: Prisma.$FilesPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    parentId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["folders"]>
  composites: {}
}

export type FoldersGetPayload<S extends boolean | null | undefined | FoldersDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FoldersPayload, S>

export type FoldersCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FoldersFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FoldersCountAggregateInputType | true
  }

export interface FoldersDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Folders'], meta: { name: 'Folders' } }
  /**
   * Find zero or one Folders that matches the filter.
   * @param {FoldersFindUniqueArgs} args - Arguments to find a Folders
   * @example
   * // Get one Folders
   * const folders = await prisma.folders.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FoldersFindUniqueArgs>(args: Prisma.SelectSubset<T, FoldersFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FoldersClient<runtime.Types.Result.GetResult<Prisma.$FoldersPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Folders that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FoldersFindUniqueOrThrowArgs} args - Arguments to find a Folders
   * @example
   * // Get one Folders
   * const folders = await prisma.folders.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FoldersFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FoldersFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FoldersClient<runtime.Types.Result.GetResult<Prisma.$FoldersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Folders that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FoldersFindFirstArgs} args - Arguments to find a Folders
   * @example
   * // Get one Folders
   * const folders = await prisma.folders.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FoldersFindFirstArgs>(args?: Prisma.SelectSubset<T, FoldersFindFirstArgs<ExtArgs>>): Prisma.Prisma__FoldersClient<runtime.Types.Result.GetResult<Prisma.$FoldersPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Folders that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FoldersFindFirstOrThrowArgs} args - Arguments to find a Folders
   * @example
   * // Get one Folders
   * const folders = await prisma.folders.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FoldersFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FoldersFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FoldersClient<runtime.Types.Result.GetResult<Prisma.$FoldersPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Folders that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FoldersFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Folders
   * const folders = await prisma.folders.findMany()
   * 
   * // Get first 10 Folders
   * const folders = await prisma.folders.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const foldersWithIdOnly = await prisma.folders.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FoldersFindManyArgs>(args?: Prisma.SelectSubset<T, FoldersFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FoldersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Folders.
   * @param {FoldersCreateArgs} args - Arguments to create a Folders.
   * @example
   * // Create one Folders
   * const Folders = await prisma.folders.create({
   *   data: {
   *     // ... data to create a Folders
   *   }
   * })
   * 
   */
  create<T extends FoldersCreateArgs>(args: Prisma.SelectSubset<T, FoldersCreateArgs<ExtArgs>>): Prisma.Prisma__FoldersClient<runtime.Types.Result.GetResult<Prisma.$FoldersPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Folders.
   * @param {FoldersCreateManyArgs} args - Arguments to create many Folders.
   * @example
   * // Create many Folders
   * const folders = await prisma.folders.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FoldersCreateManyArgs>(args?: Prisma.SelectSubset<T, FoldersCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Folders and returns the data saved in the database.
   * @param {FoldersCreateManyAndReturnArgs} args - Arguments to create many Folders.
   * @example
   * // Create many Folders
   * const folders = await prisma.folders.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Folders and only return the `id`
   * const foldersWithIdOnly = await prisma.folders.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FoldersCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FoldersCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FoldersPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Folders.
   * @param {FoldersDeleteArgs} args - Arguments to delete one Folders.
   * @example
   * // Delete one Folders
   * const Folders = await prisma.folders.delete({
   *   where: {
   *     // ... filter to delete one Folders
   *   }
   * })
   * 
   */
  delete<T extends FoldersDeleteArgs>(args: Prisma.SelectSubset<T, FoldersDeleteArgs<ExtArgs>>): Prisma.Prisma__FoldersClient<runtime.Types.Result.GetResult<Prisma.$FoldersPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Folders.
   * @param {FoldersUpdateArgs} args - Arguments to update one Folders.
   * @example
   * // Update one Folders
   * const folders = await prisma.folders.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FoldersUpdateArgs>(args: Prisma.SelectSubset<T, FoldersUpdateArgs<ExtArgs>>): Prisma.Prisma__FoldersClient<runtime.Types.Result.GetResult<Prisma.$FoldersPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Folders.
   * @param {FoldersDeleteManyArgs} args - Arguments to filter Folders to delete.
   * @example
   * // Delete a few Folders
   * const { count } = await prisma.folders.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FoldersDeleteManyArgs>(args?: Prisma.SelectSubset<T, FoldersDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Folders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FoldersUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Folders
   * const folders = await prisma.folders.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FoldersUpdateManyArgs>(args: Prisma.SelectSubset<T, FoldersUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Folders and returns the data updated in the database.
   * @param {FoldersUpdateManyAndReturnArgs} args - Arguments to update many Folders.
   * @example
   * // Update many Folders
   * const folders = await prisma.folders.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Folders and only return the `id`
   * const foldersWithIdOnly = await prisma.folders.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FoldersUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FoldersUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FoldersPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Folders.
   * @param {FoldersUpsertArgs} args - Arguments to update or create a Folders.
   * @example
   * // Update or create a Folders
   * const folders = await prisma.folders.upsert({
   *   create: {
   *     // ... data to create a Folders
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Folders we want to update
   *   }
   * })
   */
  upsert<T extends FoldersUpsertArgs>(args: Prisma.SelectSubset<T, FoldersUpsertArgs<ExtArgs>>): Prisma.Prisma__FoldersClient<runtime.Types.Result.GetResult<Prisma.$FoldersPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Folders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FoldersCountArgs} args - Arguments to filter Folders to count.
   * @example
   * // Count the number of Folders
   * const count = await prisma.folders.count({
   *   where: {
   *     // ... the filter for the Folders we want to count
   *   }
   * })
  **/
  count<T extends FoldersCountArgs>(
    args?: Prisma.Subset<T, FoldersCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FoldersCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Folders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FoldersAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FoldersAggregateArgs>(args: Prisma.Subset<T, FoldersAggregateArgs>): Prisma.PrismaPromise<GetFoldersAggregateType<T>>

  /**
   * Group by Folders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FoldersGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FoldersGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FoldersGroupByArgs['orderBy'] }
      : { orderBy?: FoldersGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FoldersGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFoldersGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Folders model
 */
readonly fields: FoldersFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Folders.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FoldersClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  parent<T extends Prisma.Folders$parentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Folders$parentArgs<ExtArgs>>): Prisma.Prisma__FoldersClient<runtime.Types.Result.GetResult<Prisma.$FoldersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  children<T extends Prisma.Folders$childrenArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Folders$childrenArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FoldersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  files<T extends Prisma.Folders$filesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Folders$filesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FilesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Folders model
 */
export interface FoldersFieldRefs {
  readonly id: Prisma.FieldRef<"Folders", 'String'>
  readonly name: Prisma.FieldRef<"Folders", 'String'>
  readonly parentId: Prisma.FieldRef<"Folders", 'String'>
  readonly createdAt: Prisma.FieldRef<"Folders", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Folders", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Folders findUnique
 */
export type FoldersFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folders
   */
  select?: Prisma.FoldersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Folders
   */
  omit?: Prisma.FoldersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FoldersInclude<ExtArgs> | null
  /**
   * Filter, which Folders to fetch.
   */
  where: Prisma.FoldersWhereUniqueInput
}

/**
 * Folders findUniqueOrThrow
 */
export type FoldersFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folders
   */
  select?: Prisma.FoldersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Folders
   */
  omit?: Prisma.FoldersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FoldersInclude<ExtArgs> | null
  /**
   * Filter, which Folders to fetch.
   */
  where: Prisma.FoldersWhereUniqueInput
}

/**
 * Folders findFirst
 */
export type FoldersFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folders
   */
  select?: Prisma.FoldersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Folders
   */
  omit?: Prisma.FoldersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FoldersInclude<ExtArgs> | null
  /**
   * Filter, which Folders to fetch.
   */
  where?: Prisma.FoldersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Folders to fetch.
   */
  orderBy?: Prisma.FoldersOrderByWithRelationInput | Prisma.FoldersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Folders.
   */
  cursor?: Prisma.FoldersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Folders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Folders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Folders.
   */
  distinct?: Prisma.FoldersScalarFieldEnum | Prisma.FoldersScalarFieldEnum[]
}

/**
 * Folders findFirstOrThrow
 */
export type FoldersFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folders
   */
  select?: Prisma.FoldersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Folders
   */
  omit?: Prisma.FoldersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FoldersInclude<ExtArgs> | null
  /**
   * Filter, which Folders to fetch.
   */
  where?: Prisma.FoldersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Folders to fetch.
   */
  orderBy?: Prisma.FoldersOrderByWithRelationInput | Prisma.FoldersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Folders.
   */
  cursor?: Prisma.FoldersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Folders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Folders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Folders.
   */
  distinct?: Prisma.FoldersScalarFieldEnum | Prisma.FoldersScalarFieldEnum[]
}

/**
 * Folders findMany
 */
export type FoldersFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folders
   */
  select?: Prisma.FoldersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Folders
   */
  omit?: Prisma.FoldersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FoldersInclude<ExtArgs> | null
  /**
   * Filter, which Folders to fetch.
   */
  where?: Prisma.FoldersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Folders to fetch.
   */
  orderBy?: Prisma.FoldersOrderByWithRelationInput | Prisma.FoldersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Folders.
   */
  cursor?: Prisma.FoldersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Folders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Folders.
   */
  skip?: number
  distinct?: Prisma.FoldersScalarFieldEnum | Prisma.FoldersScalarFieldEnum[]
}

/**
 * Folders create
 */
export type FoldersCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folders
   */
  select?: Prisma.FoldersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Folders
   */
  omit?: Prisma.FoldersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FoldersInclude<ExtArgs> | null
  /**
   * The data needed to create a Folders.
   */
  data: Prisma.XOR<Prisma.FoldersCreateInput, Prisma.FoldersUncheckedCreateInput>
}

/**
 * Folders createMany
 */
export type FoldersCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Folders.
   */
  data: Prisma.FoldersCreateManyInput | Prisma.FoldersCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Folders createManyAndReturn
 */
export type FoldersCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folders
   */
  select?: Prisma.FoldersSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Folders
   */
  omit?: Prisma.FoldersOmit<ExtArgs> | null
  /**
   * The data used to create many Folders.
   */
  data: Prisma.FoldersCreateManyInput | Prisma.FoldersCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FoldersIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Folders update
 */
export type FoldersUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folders
   */
  select?: Prisma.FoldersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Folders
   */
  omit?: Prisma.FoldersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FoldersInclude<ExtArgs> | null
  /**
   * The data needed to update a Folders.
   */
  data: Prisma.XOR<Prisma.FoldersUpdateInput, Prisma.FoldersUncheckedUpdateInput>
  /**
   * Choose, which Folders to update.
   */
  where: Prisma.FoldersWhereUniqueInput
}

/**
 * Folders updateMany
 */
export type FoldersUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Folders.
   */
  data: Prisma.XOR<Prisma.FoldersUpdateManyMutationInput, Prisma.FoldersUncheckedUpdateManyInput>
  /**
   * Filter which Folders to update
   */
  where?: Prisma.FoldersWhereInput
  /**
   * Limit how many Folders to update.
   */
  limit?: number
}

/**
 * Folders updateManyAndReturn
 */
export type FoldersUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folders
   */
  select?: Prisma.FoldersSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Folders
   */
  omit?: Prisma.FoldersOmit<ExtArgs> | null
  /**
   * The data used to update Folders.
   */
  data: Prisma.XOR<Prisma.FoldersUpdateManyMutationInput, Prisma.FoldersUncheckedUpdateManyInput>
  /**
   * Filter which Folders to update
   */
  where?: Prisma.FoldersWhereInput
  /**
   * Limit how many Folders to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FoldersIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Folders upsert
 */
export type FoldersUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folders
   */
  select?: Prisma.FoldersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Folders
   */
  omit?: Prisma.FoldersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FoldersInclude<ExtArgs> | null
  /**
   * The filter to search for the Folders to update in case it exists.
   */
  where: Prisma.FoldersWhereUniqueInput
  /**
   * In case the Folders found by the `where` argument doesn't exist, create a new Folders with this data.
   */
  create: Prisma.XOR<Prisma.FoldersCreateInput, Prisma.FoldersUncheckedCreateInput>
  /**
   * In case the Folders was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FoldersUpdateInput, Prisma.FoldersUncheckedUpdateInput>
}

/**
 * Folders delete
 */
export type FoldersDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folders
   */
  select?: Prisma.FoldersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Folders
   */
  omit?: Prisma.FoldersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FoldersInclude<ExtArgs> | null
  /**
   * Filter which Folders to delete.
   */
  where: Prisma.FoldersWhereUniqueInput
}

/**
 * Folders deleteMany
 */
export type FoldersDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Folders to delete
   */
  where?: Prisma.FoldersWhereInput
  /**
   * Limit how many Folders to delete.
   */
  limit?: number
}

/**
 * Folders.parent
 */
export type Folders$parentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folders
   */
  select?: Prisma.FoldersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Folders
   */
  omit?: Prisma.FoldersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FoldersInclude<ExtArgs> | null
  where?: Prisma.FoldersWhereInput
}

/**
 * Folders.children
 */
export type Folders$childrenArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folders
   */
  select?: Prisma.FoldersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Folders
   */
  omit?: Prisma.FoldersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FoldersInclude<ExtArgs> | null
  where?: Prisma.FoldersWhereInput
  orderBy?: Prisma.FoldersOrderByWithRelationInput | Prisma.FoldersOrderByWithRelationInput[]
  cursor?: Prisma.FoldersWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FoldersScalarFieldEnum | Prisma.FoldersScalarFieldEnum[]
}

/**
 * Folders.files
 */
export type Folders$filesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Files
   */
  select?: Prisma.FilesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Files
   */
  omit?: Prisma.FilesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilesInclude<ExtArgs> | null
  where?: Prisma.FilesWhereInput
  orderBy?: Prisma.FilesOrderByWithRelationInput | Prisma.FilesOrderByWithRelationInput[]
  cursor?: Prisma.FilesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FilesScalarFieldEnum | Prisma.FilesScalarFieldEnum[]
}

/**
 * Folders without action
 */
export type FoldersDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Folders
   */
  select?: Prisma.FoldersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Folders
   */
  omit?: Prisma.FoldersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FoldersInclude<ExtArgs> | null
}
