/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports all enum related types from the schema.
 *
 * 🟢 You can import this file directly.
 */

export const UserRole = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  REGULAR: 'REGULAR',
} as const;

export type UserRole = (typeof UserRole)[keyof typeof UserRole];

export const AuthMethod = {
  CREDENTIALS: 'CREDENTIALS',
  GOOGLE: 'GOOGLE',
  YANDEX: 'YANDEX',
} as const;

export type AuthMethod = (typeof AuthMethod)[keyof typeof AuthMethod];

export const TokenType = {
  VERIFICATION: 'VERIFICATION',
  PASSWORD_RESET: 'PASSWORD_RESET',
  TWO_FACTOR: 'TWO_FACTOR',
} as const;

export type TokenType = (typeof TokenType)[keyof typeof TokenType];
